### PR TITLE
Dropdown menu for users management

### PR DESCRIPTION
**Pull request by peregrineshahin**
This implement @disservin suggestion at https://github.com/official-stockfish/fishtest/issues/1894#issuecomment-1948782740

### CODE REVIEW

**Comment by ppigazzini** [comment]
```yaml
Mar 05 08:04:14 dfts-0 pserve[30927]:   File "/home/usr00/fishtest/server/fishtest/views.py", line 560, in user_management
Mar 05 08:04:14 dfts-0 pserve[30927]:     "idle_users": get_idle_users(request, users),  # depends on cache too
Mar 05 08:04:14 dfts-0 pserve[30927]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 05 08:04:14 dfts-0 pserve[30927]:   File "/home/usr00/fishtest/server/fishtest/views.py", line 540, in get_idle_users
Mar 05 08:04:14 dfts-0 pserve[30927]:     for u in users:
Mar 05 08:04:14 dfts-0 pserve[30927]: TypeError: 'Request' object is not iterable
```

**Comment by ppigazzini** [comment]
I go offline now, I will busy for 3 days.

**Comment by peregrineshahin** [comment]
> DEV updated.

Looks good now

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Pull request merged**
