### PR TITLE
Enhance ugly design

### PR DESCRIPTION
**Pull request by peregrineshahin**
old
Capture2
vs new
Capture

### CODE REVIEW

**Comment by vondele** [comment]
while at it, maybe we don't need the registration time with microsecond resolution displayed?

**Comment by peregrineshahin** [comment]
> while at it, maybe we don't need the registration time with microsecond resolution displayed?

image

**Comment by ppigazzini** [comment]
image

**Comment by peregrineshahin** [comment]
I cannot reproduce that at all, on firefox, edge, and chrome

**Comment by peregrineshahin** [comment]
nvm I replecated that.

**Comment by peregrineshahin** [comment]
should be fixed now

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

image

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin

**Pull request merged**
