### PR TITLE
Create a purge_run event for "Auto purge".

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, running a SPRT time-odds auto-purge, one of the workers with the TCs switched to trigger the auto-purge.

**Comment by vdbergh** [comment]
Also:

Screenshot from 2023-09-06 20-51-07

**Comment by ppigazzini** [comment]
image

**Review by ppigazzini — APPROVED** [review]
LGTM on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
