### PR TITLE
cleanup the cutechess setup code

### PR DESCRIPTION
**Pull request by Disservin**
refactor the cutechess setup code a bit to make it more readable

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
Looks good on linux/windows workers, tested working:
- `cutechess-cli` clean download
- `cutechess-cli` download on `cutechess-cli` error
- `cutechess-cli` restore from backup

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @Disservin :)

**Comment by vdbergh** [comment]
The output of the worker now looks a bit strange
```
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 170.02ms (server: 0.09ms)
Obtaining version info for /home/vdbergh/fishtest/worker/testing/cutechess-cli ...
Found:  cutechess-cli 1.2.0
Obtaining version info for /home/vdbergh/fishtest/worker/testing/cutechess-cli ...
Found:  cutechess-cli 1.2.0
Downloading https://raw.githubusercontent.com/official-stockfish/fishtest/master/worker/sri.txt
```
I wonder if this is caused by this PR?

**Comment by Disservin** [comment]
Ahh yes, current:

```python
    # Download cutechess-cli if missing or overwrite if there are issues.
    if not cutechess_path.exists() or not verify_required_cutechess(cutechess_path):
        download_cutechess(cutechess, testing_dir)

    ret = True

    if not verify_required_cutechess(cutechess_path):
```

this should fix it right?
```python
    # Download cutechess-cli if missing or overwrite if there are issues.
    if not cutechess_path.exists():
        download_cutechess(cutechess, testing_dir)
   
    if verify_required_cutechess(cutechess_path)
         os.chdir(curr_dir)
         return True
    else:
        download_cutechess(cutechess, testing_dir)

    ret = True

    if not verify_required_cutechess(cutechess_path):
```

**Comment by vdbergh** [comment]
Sort of. But now it would do a pointless redownload if the downloaded cutechess-cli does not work. So the first else clause should go I think. 

Also the if clause after that becomes redundant.

**Comment by vdbergh** [comment]
Hmm but if an existing cutechess-cli does not work then it has to do the download. So my comment above is not quite right.

**Comment by vdbergh** [comment]
I think the code can also be simplified a bit by moving the check for the existence of `cutechess-cli` inside `verify_required_cutechess()`. Morally it belongs there I think.

**Comment by Disservin** [comment]
Yeah that's a good idea ;) just keep the download in the setup part. I think then it's just?
```python
    if not verify_required_cutechess(cutechess_path):
        download_cutechess(cutechess, testing_dir)
    else:
         os.chdir(curr_dir)
         return True

    ret = True

    if not verify_required_cutechess(cutechess_path):
```

**Comment by vdbergh** [comment]
Like that it seems ok to me....

**Comment by vdbergh** [comment]
Please make a PR!

**Pull request merged**
