### PR TITLE
Use the native target if available in SF

### PR DESCRIPTION
**Pull request by vondele**

### CODE REVIEW

**Comment by mstembera** [comment]
So does native know to select x86-64-avx2 on AMD/ZEN even though x86-64-bmi2 is technically supported(but slower)?

**Comment by vondele** [comment]
> So does native know to select x86-64-avx2 on AMD/ZEN even though x86-64-bmi2 is technically supported(but slower)?

yes

https://github.com/official-stockfish/Stockfish/blob/70ba9de85cddc5460b1ec53e0a99bee271e26ece/scripts/get_native_properties.sh#L36

**Comment by ppigazzini** [comment]
Linux, WSL workers show this error:
```
Downloading https://api.github.com/repos/official-stockfish/Stockfish/zipball/70ba9de85cddc5460b1ec53e0a99bee271e26ece
Build uses default net:  nn-ac1dbea57aa3.nnue
/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied
/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied
...
Flags:
CXX: clang++
CXXFLAGS: -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -Wmissing-prototypes -Wconditional-uninitialized -DUSE_PTHREADS -DNDEBUG -O3 -funroll-loops -DIS_64BIT -DNO_PREFETCH -DGIT_SHA=e6c9e3b9 -DGIT_DATE=20230923 -flto=full
LDFLAGS:   -latomic -lpthread -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17  -pedantic -Wextra -Wshadow -Wmissing-prototypes -Wconditional-uninitialized -DUSE_PTHREADS -DNDEBUG -O3 -funroll-loops -DIS_64BIT -DNO_PREFETCH -DGIT_SHA=e6c9e3b9 -DGIT_DATE=20230923 -flto=full

Testing config sanity. If this fails, try 'make help' ...


Exception running games:
Executing make -j 2 profile-build ARCH=native COMP=clang failed. Error: ['/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', '/bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied\n', 'make: *** [Makefile:988: config-sanity] Error 1\n']
Informing the server
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 136.75ms (server: 2.12ms)
Task exited
Waiting 30.0 seconds before retrying
```

**Comment by vondele** [comment]
> DEV updated, msy2 worker looks good, but Linux (colab) and WSL workers show this error (either using g++ or clang++):
> /bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied

hmm, looks like the SF Makefile doesn't work in these environments? The script has executable flags set, but maybe the first line `#!/bin/sh` causes a problem? Is there a `/bin/sh` in those environements ?

**Comment by vondele** [comment]
Can you test if something like this change to SF would work:
```
diff --git a/scripts/get_native_properties.sh b/scripts/get_native_properties.sh
index cffb0ce27..35e90a72b 100755
--- a/scripts/get_native_properties.sh
+++ b/scripts/get_native_properties.sh
@@ -1,5 +1,3 @@
-#!/bin/sh
-
 #
 # Returns properties of the native system.
 # best architecture as supported by the CPU
```
(this works on Linux).

**Comment by UniQP** [comment]
> Downloading https://api.github.com/repos/official-stockfish/Stockfish/zipball/70ba9de85cddc5460b1ec53e0a99bee271e26ece
> Build uses default net:  nn-ac1dbea57aa3.nnue
> /bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied

I think what happens here is that downloading the zipball loses the executable flag of the script. Using a tarball instead should solve the problem.

**Comment by vondele** [comment]
> > Downloading https://api.github.com/repos/official-stockfish/Stockfish/zipball/70ba9de85cddc5460b1ec53e0a99bee271e26ece
> > Build uses default net:  nn-ac1dbea57aa3.nnue
> > /bin/sh: 1: ../scripts/get_native_properties.sh: Permission denied
> 
> I think what happens here is that downloading the zipball loses the executable flag of the script. Using a tarball instead should solve the problem.

a you're right. The zipball doesn't retain those permissions... let me try something else.

**Comment by vondele** [comment]
So, this could be a solution:
```diff
diff --git a/src/Makefile b/src/Makefile
index 1b03bbc2b..95f0fe9a5 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -108,7 +108,7 @@ ifeq ($(ARCH),)
 endif
 
 ifeq ($(ARCH), native)
-   override ARCH = $(shell ../scripts/get_native_properties.sh | cut -d " " -f 1)
+   override ARCH = $(shell $(SHELL) ../scripts/get_native_properties.sh | cut -d " " -f 1)
 endif
 
 # explicitly check for the list of supported architectures (as listed with make help),
```

**Comment by ppigazzini** [comment]
All the workers (linux bmi2, wsl sse41-popcnt, msys2 sse41-popcnt) look good running SPRT `vondele:explicitShell` vs `vondele:explicitShell`

Before merging this PR as is, we should wait that all tests are using SF with the fix https://github.com/official-stockfish/Stockfish/pull/4803

I check if it's possible to add some worker code to intercept the issue.

**Comment by ppigazzini** [comment]
```diff
diff --git a/worker/games.py b/worker/games.py
index c6b82c6b..43e5a291 100644
--- a/worker/games.py
+++ b/worker/games.py
@@ -525,6 +525,7 @@ def make_targets():
         with subprocess.Popen(
             ["make", "help"],
             stdout=subprocess.PIPE,
+            stderr=subprocess.PIPE,
             universal_newlines=True,
             bufsize=1,
             close_fds=not IS_WINDOWS,
@@ -539,6 +540,16 @@ def make_targets():
                     targets.append(line.split()[0])
                 if "Supported archs:" in line:
                     read_targets = True
+
+            for line in iter(p.stderr.readline, ""):
+                if (
+                    "native" in targets
+                    and "get_native_properties.sh" in line
+                    and "Permission denied" in line
+                ):
+                    targets.remove("native")
+                    break
+
     except (OSError, subprocess.SubprocessError) as e:
         print("Exception while executing make help:\n", e, sep="", file=sys.stderr)
         raise FatalException("It appears 'make' is not properly installed")
```

**Comment by ppigazzini** [comment]
PROD updated to trigger the workers update, thank you @vondele :)

**Pull request merged**
