### PR TITLE
Make blocking and unblocking one button instead of a checkbox

### PR DESCRIPTION
**Pull request by peregrineshahin**
makes it the same button for block and unblock, 1 click is better than 2.

### CODE REVIEW

**Comment by peregrineshahin** [comment]
Dev is crashing, probably does not have the last push.

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
@vdbergh can you try it again?

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV:
- accepted a new user
- rejected a new user
- blocked an user
- unblocked an user

**Comment by vdbergh** [comment]
It seems to work.

I find it is a bit disconcerting that each time you do something in user management you are sent back to the main test page.

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Comment by vdbergh** [comment]
It is possible to make very long usernames 

Screenshot from 2023-12-10 14-46-07

I tried to make even longer ones but this seemed to fail silently, which is also not nice.

**Comment by peregrineshahin** [comment]
Well as you said, this particular user with abnormal long username will be rejected and thus will not be shown in the events log

**Comment by vdbergh** [comment]
Well I posted a screenshot from the event log.

**Comment by peregrineshahin** [comment]
> Well I posted a screenshot from the event log.

Yes that's because it was accepted, then blocked.
but normally the approver should reject him

**Comment by vdbergh** [comment]
That was what I was going to say. But it is still not nice I think. There should be some reasonable limit on the length of a username.

**Comment by peregrineshahin** [comment]
same goes for offensive usernames

**Comment by peregrineshahin** [comment]
Yeah I think limiting username length is a good thing to have

**Comment by vdbergh** [comment]
Offensive usernames are different since they cannot be rejected automatically. But usernames that are too long can.

**Comment by peregrineshahin** [comment]
Agreed! my message was delayed a bit :)

**Pull request merged**
