### PR TITLE
Make it possible to reject users before accepting them

### PR DESCRIPTION
**Pull request by peregrineshahin**
follow up for https://github.com/official-stockfish/fishtest/pull/1805

### CODE REVIEW

**Comment by ppigazzini** [comment]
IMO "Pending" needs some space

image

**Comment by peregrineshahin** [comment]
Yes I will fix the design now, just want to make sure it works first.

**Comment by ppigazzini** [comment]
I pushed "Rejected" but it was accepted?!?

**Comment by peregrineshahin** [comment]
> I pushed "Rejected" but it was accepted?!?

I accepted it before you :P

Hands off try again

**Comment by vdbergh** [comment]
IMHO the pending label is superfluous now.

**Comment by peregrineshahin** [comment]
> IMHO the pending label is superfluous now.

Yes I just pushed updates to the design

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV.

I meant the dark theme :)

image

image

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Comment by vdbergh** [comment]
I just blocked a worker on DEV (the blocking appears in the event log). However the blocked worker does not appear in the list.

**Comment by peregrineshahin** [comment]
I forgot to save user again
fixed here
https://github.com/official-stockfish/fishtest/pull/1860

> I just blocked a user on DEV (the blocking appears in the event log). However the blocked user does not appear in the list.

**Pull request merged**
