### PR TITLE
fix double cutechess verification

### PR DESCRIPTION
**Pull request by Disservin**
as discussed in https://github.com/official-stockfish/fishtest/pull/1802, this should fix the double cutechess verification

### CODE REVIEW

**Comment by vdbergh** [comment]
It is still not 100% robust. I replaced the `cutechess-cli` binary by `/bin/ps` and I got an uncaught exception
```
Obtaining version info for /home/vdbergh/fishtest/worker/testing/cutechess-cli ...
Found:  cutechess-cli from procps-ng 3.3.17
Traceback (most recent call last):
  File "/home/vdbergh/fishtest/worker/worker.py", line 1668, in <module>
    sys.exit(worker())
  File "/home/vdbergh/fishtest/worker/worker.py", line 1570, in worker
    if not setup_cutechess(worker_dir):
  File "/home/vdbergh/fishtest/worker/worker.py", line 471, in setup_cutechess
    if not verify_required_cutechess(cutechess_path):
  File "/home/vdbergh/fishtest/worker/worker.py", line 428, in verify_required_cutechess
    major = int(m.group(1))
ValueError: invalid literal for int() with base 10: ''
Deleting lock file /home/vdbergh/fishtest/worker/worker.lock
```

**Comment by Disservin** [comment]
Well that's outside the scope of this pr, since that never worked, right?

**Comment by vdbergh** [comment]
If we replace `cutechess-cli` by `/bin/ps` then `cutechess-cli --version` yields
```
cutechess-cli from procps-ng 3.3.17
```
So `/bin/ps` does some funky stuff with its zeroth argument.

**Comment by vdbergh** [comment]
> Well that's outside the scope of this pr, since that never worked, right?

I guess so. But tightening the regular expression a little bit fixes it
```python
pattern = re.compile("cutechess-cli ([0-9]+)\.([0-9]+)\.([0-9]+)")
```

**Review by ppigazzini — APPROVED** [review]
Looks good on linux/msys2 worker.
Tightened the regex as well.

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @Disservin :)

**Pull request merged**
