### PR TITLE
Add "Content-Length" header for run PGN

### PR DESCRIPTION
**Pull request by ppigazzini**
Improve https://github.com/official-stockfish/fishtest/pull/1955

### CODE REVIEW

**Comment by ppigazzini** [comment]
```
usr00@pp-wrk-00:~/_tests_size$ wget https://dfts-0.pigazzini.it/api/run_pgns/662cbc0ce58b87631ba593c3.pgn.gz
--2024-04-27 11:03:29--  https://dfts-0.pigazzini.it/api/run_pgns/662cbc0ce58b87631ba593c3.pgn.gz
Resolving dfts-0.pigazzini.it (dfts-0.pigazzini.it)... 94.198.98.133
Connecting to dfts-0.pigazzini.it (dfts-0.pigazzini.it)|94.198.98.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2414993 (2.3M) [application/gzip]
Saving to: ‘662cbc0ce58b87631ba593c3.pgn.gz’

662cbc0ce58b87631ba593c3.pgn. 100%[=================================================>]   2.30M  2.71MB/s    in 0.9s

2024-04-27 11:03:30 (2.71 MB/s) - ‘662cbc0ce58b87631ba593c3.pgn.gz’ saved [2414993/2414993]

usr00@pp-wrk-00:~/_test_size$ ls -la
total 2368
drwxr-xr-x  2 usr00 usr00    4096 Apr 27 11:03 .
drwxr-x--- 40 usr00 usr00    4096 Apr 27 10:53 ..
-rw-r--r--  1 usr00 usr00 2414993 Apr 27 11:03 662cbc0ce58b87631ba593c3.pgn.gz
```

**Comment by peregrineshahin** [comment]
That's exactly what I had in mind.. but I wonder how much time the aggregation takes..

**Comment by peregrineshahin** [comment]
What I was thinking too, is probably it would be better schema wise.. is if we have two fields.. one refers to the pgn id and one refers to the run id. In such way we could ditch the dependence on regexes and benefit from two indexing.
But Im not sure how slow is current query.

**Comment by ppigazzini** [comment]
> What I was thinking too, is probably it would be better schema wise.. is if we have two fields.. one refers to the pgn id and one refers to the run id. In such way we could ditch the dependence on regexes and benefit from two indexing. But Im not sure how slow is current query.

```
diff --git a/server/fishtest/rundb.py b/server/fishtest/rundb.py
index 524f555..872d553 100644
--- a/server/fishtest/rundb.py
+++ b/server/fishtest/rundb.py
@@ -274,12 +274,14 @@ class RunDb:
             # Create a generator that yields each pgn.gz file
             pgn_generator = (pgn["pgn_zip"] for pgn in pgns)
             # Compute the total size using MongoDB's aggregation framework
+            t0 = time.time()
             total_size = self.pgndb.aggregate(
                 [
                     {"$match": {"run_id": {"$regex": f"^{run_id}"}}},
                     {"$group": {"_id": None, "totalSize": {"$sum": "$size"}}},
                 ]
             ).next()["totalSize"]
+            print(time.time() - t0, flush=True)
             return GeneratorAsFileReader(pgn_generator), total_size
         return None, 0
```


```
wget https://dfts-0.pigazzini.it/api/run_pgns/662a442b6c6057d3bbd2978f.pgn.gz
--2024-04-27 11:27:19--  https://dfts-0.pigazzini.it/api/run_pgns/662a442b6c6057d3bbd2978f.pgn.gz
Resolving dfts-0.pigazzini.it (dfts-0.pigazzini.it)... 94.198.98.133
Connecting to dfts-0.pigazzini.it (dfts-0.pigazzini.it)|94.198.98.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 204137873 (195M) [application/gzip]
Saving to: ‘662a442b6c6057d3bbd2978f.pgn.gz’

662a442b6c6057d3bbd2978f.pgn. 100%[=================================================>] 194.68M  12.0MB/s    in 17s

2024-04-27 11:27:37 (11.2 MB/s) - ‘662a442b6c6057d3bbd2978f.pgn.gz’ saved [204137873/204137873]
```


```
Apr 27 11:27:15 dfts-0 systemd[1]: Stopped Fishtest Server port 6545.
Apr 27 11:27:15 dfts-0 systemd[1]: Started Fishtest Server port 6545.
Apr 27 11:27:16 dfts-0 pserve[4933]: Starting server in PID 4933.
Apr 27 11:27:20 dfts-0 pserve[4933]: 0.00289154052734375
```

**Comment by peregrineshahin** [comment]
Makes sense, so they are naturally indexed in a way, also the aggregation seems to do a great minimalistic job! Yhanks for the reply

**Comment by ppigazzini** [comment]
Companion script
```python
from fishtest.rundb import RunDb

def add_size_key(rundb):
    pgns_without_size = rundb.pgndb.find({"size": {"$exists": False}})

    for pgn in pgns_without_size:
        size = len(pgn["pgn_zip"])
        rundb.pgndb.update_one({"_id": pgn["_id"]}, {"$set": {"size": size}})

def main():
    rundb = RunDb()
    add_size_key(rundb)

if __name__ == "__main__":
    main()
```

**Comment by ppigazzini** [comment]
> Makes sense, so they are naturally indexed in a way, also the aggregation seems to do a great minimalistic job! Thanks for the reply

MMMM, the pgns collection on DEV is nearly empty, we need to test the time with the PROD collection...

**Comment by ppigazzini** [comment]
Aggregation time computed on PROD, the first has 17 tasks/7k games, the second has 438 tasks/339k games
```
Apr 27 11:04:46 tests.stockfishchess.org pserve[21401]: Aggregation time: 0.03008127212524414
Apr 27 11:05:53 tests.stockfishchess.org pserve[21401]: Aggregation time: 1.187739372253418
```

**Comment by ppigazzini** [comment]
@robertnurnberg PROD updated by hand, it's ready to be tested with your tool.

**Comment by vondele** [comment]
Works:
```
starting download at  Sa 27 Apr 2024 13:27:03 CEST
Found 6986 downloaded tests in ./pgns/ already.
Collecting meta data for test 662574a93fe04ce4cefc3afc ...
Downloading 128MB .pgn.gz file with 123810 games (WDL = 31738 60743 31329) to ./pgns/24-04-21/662574a93fe04ce4cefc3afc/ ...
Collecting meta data for test 6627b71e3fe04ce4cefc60e0 ...
Downloading 27MB .pgn.gz file with 26484 games (WDL = 6722 13081 6681) to ./pgns/24-04-23/6627b71e3fe04ce4cefc60e0/ ...
```
matching the download size 
```
$ ls -tlr ./pgns/24-04-21/662574a93fe04ce4cefc3afc/662574a93fe04ce4cefc3afc.pgn.gz 
-rw-rw-r-- 1 vondele vondele 128237134 Apr 27 13:27 ./pgns/24-04-21/662574a93fe04ce4cefc3afc/662574a93fe04ce4cefc3afc.pgn.gz
```

**Comment by robertnurnberg** [comment]
Works perfectly also here. Thanks a lot. @ppigazzini

**Comment by ppigazzini** [comment]
PROD updated.

**Comment by vdbergh** [comment]
I think run_id is not really the correct name for the field since it seems to also contain the task id (so it would need a different regex). Perhaps we can use two fields run_id+task_id as is done elsewhere in fishtest?

**Comment by peregrineshahin** [comment]
> I think run_id is not really the correct name for the field since it seems to also contain the task id (so it would need a different regex). Perhaps we can use two fields run_id+task_id as is done elsewhere in fishtest?

Well that's what I said here, but probably it's too much work to convert old pgns
```
What I was thinking too, is probably it would be better schema wise.. is if we have two fields.. one refers to the pgn id and one refers to the run id. In such way we could ditch the dependence on regexes and benefit from two indexing.
But Im not sure how slow is current query.
```

**Comment by vdbergh** [comment]
> Well that's what I said here, but probably it's too much work to convert old pgns

I guess that would be the case. Adding a new regex `run_id_pgns` is not the end of the world.

**Comment by peregrineshahin** [comment]
Not sure I understood, yes I think current situation is okay.. but if you refer to your suggestion then you don't need regexes at all as the query will be strict equality.

> I guess that would be the case. Adding a new regex `run_id_pgns` is not the end of the world.

**Comment by ppigazzini** [comment]
`run_id` is wrong (the first time I worked on that code it was confusing), `pgn_zip` is inaccurate as well (`pgn_gz` is better).

**Pull request merged**
