### PR TITLE
Some html fixes.

### PR DESCRIPTION
**Pull request by peregrineshahin**
removes extra spaces, adds a placeholder to SPSA params textarea, and removes unnecessary usage of HTML non-breaking space.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by peregrineshahin** [comment]
looks fine no?

**Comment by ppigazzini** [comment]
DEV updated after https://github.com/official-stockfish/fishtest/pull/1766/commits/71247395529748b689ed27b5310ac8730e692bbe

**Comment by ppigazzini** [comment]
It looks good in PC browser.

**Review by ppigazzini — APPROVED** [review]
LGTM on DEV

**Pull request merged**
