### PR TITLE
Add menu for blocked workers

### PR DESCRIPTION
**Pull request by peregrineshahin**
Also Enhances filterTable clientside function to take a predicate instead of always includes
Closes https://github.com/official-stockfish/fishtest/issues/1894

### CODE REVIEW

**Comment by ppigazzini** [comment]
The dropdown seems to be stuck on "Modified <= 5 days ago"

image

**Comment by ppigazzini** [comment]
Uncaught (in promise) TypeError

image

**Comment by peregrineshahin** [comment]
should be fixed

**Comment by ppigazzini** [comment]
Filtering is text based on "days ago", but we should consider "seconds" and "hours" as well. 


image

**Comment by peregrineshahin** [comment]
should be fixed.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin

**Pull request merged**
