### PR TITLE
Tighten up parsing of "Finished game" lines in cutechess-cli output.

### PR DESCRIPTION
**Pull request by vdbergh**
See https://tests.stockfishchess.org/actions?max_actions=3&text=%22update_pentanomial%22&before=1695591050.683729

### CODE REVIEW

**Comment by vdbergh** [comment]
The third of these messages is a bit disturbing. 

- In UCI an engine cannot claim a result. So this suggest an internal bug in cutechess-cli.
- Apparently sometimes error messages and genuine output message are not interleaved cleanly (this is maybe not unexpected as they are written to different streams which are merged by Python).

**Comment by vdbergh** [comment]
Actually the other cases recorded in the event log URL appear to be of similar nature. Unclean interleaving of error and non-error messages.

**Comment by vdbergh** [comment]
Independently of this PR. I wonder if it would not be better to poll both p.stderr and p.stdout in the worker, instead of relying on Python to merge the streams for us.

**Review by ppigazzini — APPROVED** [review]

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @vdbergh :)

**Pull request merged**
