### PR TITLE
Show approvers to user management

### PR DESCRIPTION
**Pull request by peregrineshahin**
and enhance the page with count statistics

image

### CODE REVIEW

**Comment by peregrineshahin** [comment]
now one thing to add to the schema is `last_action`, but it requires getting the users and updating it on each action as well.
which I will do in a different PR based on @vondele suggestion.

**Comment by peregrineshahin** [comment]
well, now I realize we have already an actions collection, can benefit from that instead no?

**Comment by peregrineshahin** [comment]
thing is the last_updated in the contributors section is not even related to the user, it's part of the workers schema..

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by vondele** [comment]
interestingly, one approver ([protonspring](https://tests.stockfishchess.org/user/protonspring)) seems to have a double group 'approvers, approvers'

**Comment by ppigazzini** [comment]
fixed

**Pull request merged**
