### PR TITLE
Partial fix for #2064.

### PR DESCRIPTION
**Pull request by vdbergh**
I had to sacrifice including `base.mak` since I do not know how to do it conditionally.

### CODE REVIEW

**Comment by peregrineshahin** [comment]
This can be done much cleaner, let me try a fix now that you inspired me how to actually get back the json and make the content type json conditionally.

**Comment by vdbergh** [comment]
The issue is not the content type but the fact that inheriting from `base.mak` happens unconditionally.

**Comment by vdbergh** [comment]
Anyway I happy to see a better fix.

**Comment by peregrineshahin** [comment]
returning a new Response already escapes the renderer as per how pyramid works

**Comment by vdbergh** [comment]
> returning a new Response already escapes the renderer as per how pyramid works

Ah ok! That's much better.

**Comment by vdbergh** [comment]
I will close this, waiting for your PR.

**Pull request closed without merging**
