### PR TITLE
Fix formula for time losses

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by peregrineshahin** [comment]
oh so this is why the message had > 100% time losses.

**Comment by vdbergh** [comment]
And more crashes than games...

**Comment by ppigazzini** [comment]
A time loss is already accounted as a win for the other side, so hacking a side to play with a smaller time control in a NumGames, the event shows a 50% of time losses (IMO confusing). Master shows a 100% of time losses.
- PR
image
- master
image

**Comment by vdbergh** [comment]
Ah yes. I missed this trivial point. What about crashes?

**Comment by vdbergh** [comment]
I guess a crash is probably also recorded as a loss.

**Comment by ppigazzini** [comment]
> Ah yes. I missed this trivial point. What about crashes?

The worker has checks and self-healing code, so I unsuccessfully hacked on the fly the nnue files to trigger the crashes.

**Comment by vdbergh** [comment]
I think cutechess-cli is started with an option to restart crashed engines. Perhaps this has something to do with it?

**Comment by vdbergh** [comment]
Btw I am in California so it is night here.

**Comment by ppigazzini** [comment]
worker hacked to always have a crash for the new side:
```diff
diff --git a/worker/games.py b/worker/games.py
index f2e452b..dd54f7e 100644
--- a/worker/games.py
+++ b/worker/games.py
@@ -1347,8 +1347,9 @@ def run_games(worker_info, password, remote, run, task_id, pgn_file, clear_binar
         establish_validated_net(remote, testing_dir, net)

     for option, net in required_nets(new_engine).items():
+        net = "abcdef012345.nnue"
         new_options.append("option.{}={}".format(option, net))
-        establish_validated_net(remote, testing_dir, net)
+        #establish_validated_net(remote, testing_dir, net)

     # PGN files output setup.
     pgn_name = "results-" + worker_info["unique_key"] + ".pgn"
```

crashes account for wins/losses as well, PR at 50%, master at 100%
image
-PR
image

- master
image

**Comment by ppigazzini** [comment]
worker hacked to always have a crash for the new side:
```diff
diff --git a/worker/games.py b/worker/games.py
index f2e452b..dd54f7e 100644
--- a/worker/games.py
+++ b/worker/games.py
@@ -1347,8 +1347,9 @@ def run_games(worker_info, password, remote, run, task_id, pgn_file, clear_binar
         establish_validated_net(remote, testing_dir, net)

     for option, net in required_nets(new_engine).items():
+        net = "abcdef012345.nnue"
         new_options.append("option.{}={}".format(option, net))
-        establish_validated_net(remote, testing_dir, net)
+        #establish_validated_net(remote, testing_dir, net)

     # PGN files output setup.
     pgn_name = "results-" + worker_info["unique_key"] + ".pgn"
```

**Comment by vdbergh** [comment]
So I guess I need to close this then. Thanks for testing and sorry for the noise.

**Pull request closed without merging**
