### PR TITLE
Do not hold on to the run_cache_lock while writing to the db.

### PR DESCRIPTION
**Pull request by vdbergh**
Use the per-run active_run_lock instead.

### CODE REVIEW

**Comment by vondele** [comment]
I'm trying to understand this a bit (not knowing this code well).. so with this, somebody can own the run_cache_lock, and modify `run` while at the same time the owner of `active_run_lock` might be writing that run to disk?

**Comment by vdbergh** [comment]
Here is how I see it.

The holder of the `run_cache_lock` should not change the actual runs, just the metadata about those runs in the cache (I do not exclude that there are bugs of course).

All modifications to actual run objects (or access to more than one property) should be done by grabbing the corresponding `active_run_lock` (again I do not exclude that there might be bugs).

When we need to write a run to the db we also need to grab the `active_run_lock`, otherwise we risk the run being modified midflight, potentially leading to a run on disk with incorrect aggregated data.

**Comment by vdbergh** [comment]
Actually it seems that in mongod single document writes are atomic https://www.mongodb.com/docs/manual/tutorial/model-data-for-atomic-operations/ . Not sure if pymongo honors that.

**Comment by vondele** [comment]
> Here is how I see it.
> 
> The holder of the `run_cache_lock` should not change the actual runs, just the metadata about those runs in the cache (I do not exclude that there are bugs of course).
> 
> All modifications to actual run objects (or access to more than one property) should be done by grabbing the corresponding `active_run_lock` (again I do not exclude that there might be bugs).
> 
> When we need to write a run to the db we also need to grab the `active_run_lock`, otherwise we risk the run being modified midflight, potentially leading to a run on disk with incorrect aggregated data.

OK, I think I understand what the approach is.

**Comment by ppigazzini** [comment]
Looks good on DEV, testing on PROD with many workers.

**Review by ppigazzini — APPROVED** [review]
Already running on PROD, it looks good.
Thank you @vdbergh

**Pull request merged**
