### PR TITLE
Update cdn's versions.

### PR DESCRIPTION
**Pull request by peregrineshahin**
bootstrap 5.3.1
highlight js 11.8.0
font awesome 6.4.2

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated, it doesn't work out of the box.

image

image

**Comment by peregrineshahin** [comment]
> DEV updated, it doesn't work out of the box.
> 
> image
> 
> image

Try now.

**Review by ppigazzini — APPROVED** [review]
DEV looks good to me.

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Pull request merged**
