### PR TITLE
Switch from cutechess-cli to fast-chess (II)

### PR DESCRIPTION
**Pull request by vondele**
Alternative to (or continuation on top of) https://github.com/official-stockfish/fishtest/pull/2119

This takes the transition a step further and uses the capability of fast-chess to output the pentanomials. As a result some of the worker code can be simplified.

### CODE REVIEW

**Comment by vondele** [comment]
@vdbergh you might want to have a careful look at this.

**Comment by vdbergh** [comment]
I had a look and everything seems fine. It is more robust that the previous code which - IIRC - relied on the fact that cutechess schedules games in a game pair consecutively to obtain the pentanomial frequencies. 

The server will reject results with incompatible WLD and pentanomial frequencies (this amounts to checking some equalities and some inequalities). So that is also a good check.

**Comment by vondele** [comment]
OK, good to know that the server does that check. 

Yes, in that case, it almost certainly is fine, and I would tend to prefer this PR directly over https://github.com/official-stockfish/fishtest/pull/2119 ... no need to go in 2 steps.

**Comment by vondele** [comment]
closing this PR, integrating it directly in #2119

**Pull request closed without merging**
