### PR TITLE
Update memory estimates

### PR DESCRIPTION
**Pull request by vondele**
after the various net updates the estimated memory need was no longer accurate also add the estimated size of cutechess-cli with the larger book

### CODE REVIEW

**Comment by vondele** [comment]
looks like the black version I used is no longer the one used here.

**Comment by ppigazzini** [comment]
> looks like the black version I used is no longer the one used here.

I will format the code when testing the PR.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV + workers

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @vondele

**Pull request merged**
