### PR TITLE
Invalidate a blocked user session

### PR DESCRIPTION
**Pull request by peregrineshahin**
This fixes a security concern (a blocked user is still able to submit tests.)
This logs the user out immediately with any interaction with the server if the user is blocked

### CODE REVIEW

**Comment by peregrineshahin** [comment]
@vdbergh I wonder if this will be too detrimental for the blocked user worker machine if they had any since now I see that I put the subscriber on all apis/views I think and redirect tot the home page, but the worker does not deal with web views?
That being said I'm not sure we should be concerned about their workers if we blocked them :P

**Comment by peregrineshahin** [comment]
Worker interaction looks very clean
```
Found g++ version 13.1.0
Found clang++ version 17.0.6
machine_id e9a3d753-7e8a-4bca-bf01-ffbf1178b6ba obtained from HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\MachineGuid
Default uuid_prefix: 05f38cf0
Worker version 232 connecting to http://172.23.43.179:80
Confirming cached credentials with http://172.23.43.179:80
Error from remote: /api/request_version: Account blocked for user: user01

Username:
```

**Comment by peregrineshahin** [comment]
Ofc the main goal of this PR is invalidating credintials of the blocked user so they can't submit tests or do any action,
but here is the result also for blocking the user while the worker is running, all looks clean.

```
-DGIT_DATE=20240409 -DARCH=x86-64-bmi2 -flto -flto-partition=one   -c -o nnue_misc.o nnue/nnue_misc.cpp
x86_64-w64-mingw32-c++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -pedantic -Wextra -Wshadow -Wmissing-declarations -DNDEBUG -O3 -funroll-loops -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -mbmi -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -DGIT_SHA=3fd98a2f -DGIT_DATE=20240409 -DARCH=x86-64-bmi2 -flto -flto-partition=one   -c -o half_ka_v2_hm.o nnue/features/half_ka_v2_hm.cpp
x86_64-w64-mingw32-c++ -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -pedantic -Wextra -Wshadow -Wmissing-declarations -DNDEBUG -O3 -funroll-loops -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -mbmi -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -DGIT_SHA=3fd98a2f -DGIT_DATE=20240409 -DARCH=x86-64-bmi2 -flto -flto-partition=one   -c -o network.o nnue/network.cpp
x86_64-w64-mingw32-c++ -o stockfish.exe benchmark.o bitboard.o evaluate.o main.o misc.o movegen.o movepick.o position.o search.o thread.o timeman.o tt.o uci.o ucioption.o tune.o tbprobe.o nnue_misc.o half_ka_v2_hm.o network.o  -lgcov -static -DNNUE_EMBEDDING_OFF -Wall -Wcast-qual -fno-exceptions -std=c++17 -fprofile-generate=profdir -pedantic -Wextra -Wshadow -Wmissing-declarations -DNDEBUG -O3 -funroll-loops -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -mbmi -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DUSE_PEXT -mbmi2 -DGIT_SHA=3fd98a2f -DGIT_DATE=20240409 -DARCH=x86-64-bmi2 -flto -flto-partition=one -save-temps
  Send heartbeat for 05f38cf0-24b8-4380-8c5a-1e1cd2d7479d ... Error from remote: /api/beat: Account blocked for user: user01
Heartbeat stopped
```

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV


```
Score of New-4912f5b0b5 vs Base-4912f5b0b5: 25 - 25 - 33  [0.500] 83
Started game 86 of 174 (Base-4912f5b0b5 vs New-4912f5b0b5)
Finished game 84 (Base-4912f5b0b5 vs New-4912f5b0b5): 1-0 {White wins by adjudication}
Score of New-4912f5b0b5 vs Base-4912f5b0b5: 25 - 26 - 33  [0.494] 84
Error from remote: /api/update_task: Account blocked for user: user09
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 168.36ms (server: 0.25ms)

Waiting for cutechess-cli to finish ... done

Exception running games:
Too many failed update attempts
Informing the server
Error from remote: /api/failed_task: Account blocked for user: user09
Post request https://dfts-0.pigazzini.it:443/api/failed_task handled in 106.03ms (server: 0.64ms)
Uploading compressed PGN of 109872 bytes
Error from remote: /api/upload_pgn: Account blocked for user: user09
Post request https://dfts-0.pigazzini.it:443/api/upload_pgn handled in 133.89ms (server: 0.75ms)
Task exited
Waiting 15.0 seconds before retrying
Current time is 2024-04-13 15:23:22.203246+00:00 UTC (local offset: +02:00)
Verify worker version...
Error from remote: /api/request_version: Account blocked for user: user09
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 160.55ms (server: 0.23ms)
Waiting for the heartbeat thread to finish...
Heartbeat stopped
Deleting lock file /home/usr00/_git/__test_folder00/fishtest/worker/worker.lock
```

```
______ _     _     _            _                        _
|  ___(_)   | |   | |          | |                      | |
| |_   _ ___| |__ | |_ ___  ___| |_  __      _____  _ __| | _____ _ __
|  _| | / __| '_ \| __/ _ \/ __| __| \ \ /\ / / _ \| '__| |/ / _ \ '__|
| |   | \__ \ | | | ||  __/\__ \ |_   \ V  V / (_) | |  |   <  __/ |
\_|   |_|___/_| |_|\__\___||___/\__|   \_/\_/ \___/|_|  |_|\_\___|_|

Worker started in /home/usr00/_git/__test_folder00/fishtest/worker ... (PID=13372)
Creating lock file /home/usr00/_git/__test_folder00/fishtest/worker/worker.lock
Found g++ version 13.1.0
Found clang++ version 18.1.3
machine_id 5c11baf2370e45fd84c27ea751358316 obtained from /etc/machine-id
Default uuid_prefix: f5d8bb50
Worker version 232 connecting to https://dfts-0.pigazzini.it:443
Confirming supplied credentials with https://dfts-0.pigazzini.it:443
Error from remote: /api/request_version: Account blocked for user: user09

Username:
```

**Comment by ppigazzini** [comment]
PRDO updated, thank you @peregrineshahin

**Pull request merged**
