### PR TITLE
Merge cutechess-cli stdout and stderr inside the worker instead of relying on Python to do it

### PR DESCRIPTION
**Pull request by vdbergh**
See the comments for #1815 .

This PR seems to work fine when the only messages are on stdout. Not tested yet when there are actually error messages. 

One way to do it is to create a test with an option unknown to SF.

### CODE REVIEW

**Comment by vdbergh** [comment]
I did the test on DEV and it works https://dfts-0.pigazzini.it/actions?max_actions=1&action=&user=&text=&before=1695643814.247783&run_id=
```
 Cutechess-cli says: "Warning: New-22cdb6c1ea doesn't have option blabla"
```

**Comment by vdbergh** [comment]
I undrafted the PR since I think it works as intended.

**Comment by vdbergh** [comment]
Hmm. I reread that discussion but I don't think I ever said I was opposed to two pipes (I can't see why I would be opposed to that).

**Comment by vdbergh** [comment]
> I wonder what it the advantages to add code to still have 2 pipes merged in only one queue.

See the comments in https://github.com/official-stockfish/fishtest/pull/1815 . Python does not merge the two streams at line breaks (output from stdout appears in the middle of output from stderr).

**Comment by vdbergh** [comment]
> I need to test this on msys2 where the stderr was delayed after the stdout.

I think this should be regarded as a bug in msys2. I don't think the PR will help with that (unless the cause is a bug in the msys2 Python). In practice this appears to be not a problem since there are enough non-msys2 workers...

**Comment by ppigazzini** [comment]
> > I wonder what it the advantages to add code to still have 2 pipes merged in only one queue.
> 
> See the comments in #1815 . Python does not merge the two streams at line breaks (output from stdout appears in the middle of output from stderr).

Thank you, I missed that comment.

**Comment by ppigazzini** [comment]
> I think this should be regarded as a bug in msys2. I don't think the PR will help with that (unless the cause is a bug in the msys2 Python). In practice this appears to be not a problem since there are enough non-msys2 workers...

No, it's cutechess-cli, not msys2 or msys2's python

**Comment by ppigazzini** [comment]
Queued a SPSA with a missing paparemeter, the linux/wsl workers stop without playing games because thecutechess-cli warning about the missing parameter.
The Windows worker plays a whole SPSA batch of games, posts the result to the server, and only then exits for the missing parameter.
I will check if it has the same behavior with master (I think so).
```
Step 4/4. Deleting profile data ...
make ARCH=x86-64-sse41-popcnt COMP=mingw profileclean
make[1]: Entering directory '/home/Pasquale Pigazzini/_git/__test_folder01/fishtest/worker/tmpbud0wa0h/Viren6-Stockfish-196ca9c/src'
make[1]: Leaving directory '/home/Pasquale Pigazzini/_git/__test_folder01/fishtest/worker/tmpbud0wa0h/Viren6-Stockfish-196ca9c/src'
strip stockfish.exe
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
CPU factor : 1.276196933139245 - tc adjusted to 76.572+0.766
CPU factor : 1.276196933139245 - tc adjusted to 1.276+0.013
CPU factor : 1.276196933139245 - tc adjusted to 1.276+0.013
Post request https://dfts-0.pigazzini.it:443/api/request_spsa handled in 533.63ms (server: 0.41ms)
TC limit 102.0957546511396 End time: 2023-09-25 19:54:39.118907+00:00
Indexing opening suite...
Started game 1 of 8 (New-196ca9c772 vs Base-196ca9c772)
Started game 2 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 1 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 1  [0.500] 1
Started game 3 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 2 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 2  [0.500] 2
Started game 4 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 3 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 3  [0.500] 3
Started game 5 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 5 (New-196ca9c772 vs Base-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 0 - 3  [0.625] 4
Started game 6 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 4 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 0 - 4  [0.600] 5
Started game 7 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 6 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 1 - 4  [0.500] 6
Started game 8 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 7 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 1 - 5  [0.500] 7
Finished game 8 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 2 - 5  [0.438] 8
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 485.25ms (server: 0.32ms)
...      New-196ca9c772 playing White: 1 - 0 - 3  [0.625] 4
...      New-196ca9c772 playing Black: 0 - 2 - 2  [0.250] 4
...      White vs Black: 3 - 0 - 5  [0.688] 8
Elo difference: -43.7 +/- 156.7, LOS: 28.2 %, DrawRatio: 62.5 %
Finished match
Finished match cleanly
Warning: Base-196ca9c772 doesn't have option AAA

Waiting for cutechess-cli to finish ... done

Exception running games:
Cutechess-cli says: "Warning: Base-196ca9c772 doesn't have option AAA"
Informing the server
Error from remote: /api/stop_run: User user01 has too few games to stop a run
Post request https://dfts-0.pigazzini.it:443/api/stop_run handled in 485.60ms (server: 5.18ms)
Task exited
Waiting 15.0 seconds before retrying
```

**Comment by vdbergh** [comment]
> > I think this should be regarded as a bug in msys2. I don't think the PR will help with that (unless the cause is a bug in the msys2 Python). In practice this appears to be not a problem since there are enough non-msys2 workers...
> 
> No, it's cutechess-cli, not msys2 or msys2's python

Why are you so sure about this?

It could be that the output of cutechess-cli to stderr is buffered on windows. But why?

**Comment by ppigazzini** [comment]
> > No, it's cutechess-cli, not msys2 or msys2's python
> 
> Why are you so sure about this?
> 
> It could be that the output of cutechess-cli to stderr is buffered on windows. But why?

In my past test it was our `cutechess-cli` static binary bult with msys2. I tried unsuccessfully every option found on the web to fix the behavior. If I recall correctly the official `cutechess-cli` (with dll) was not affected from the problem.
By the way the new static `cutechess-cli 1.3.1` has the same behavior with the PR, the output of `cutechess-cli` seem to be changed.

```
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
CPU factor : 1.2857007973353851 - tc adjusted to 77.142+0.771
CPU factor : 1.2857007973353851 - tc adjusted to 1.286+0.013
CPU factor : 1.2857007973353851 - tc adjusted to 1.286+0.013
Post request https://dfts-0.pigazzini.it:443/api/request_spsa handled in 499.78ms (server: 0.26ms)
TC limit 102.85606378683082 End time: 2023-09-25 20:11:19.540156+00:00
Indexing opening suite...
Started game 1 of 8 (New-196ca9c772 vs Base-196ca9c772)
Started game 2 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 2 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 1  [0.500] 1
Started game 3 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 1 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 2  [0.500] 2
Started game 4 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 3 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by 3-fold repetition}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 3  [0.500] 3
Started game 5 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 4 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 1 - 3  [0.375] 4
Started game 6 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 5 (New-196ca9c772 vs Base-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 1 - 3  [0.500] 5
Started game 7 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 6 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 2 - 3  [0.417] 6
Started game 8 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 7 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 2 - 4  [0.429] 7
Finished game 8 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 2 - 5  [0.438] 8
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 506.25ms (server: 0.27ms)
...      New-196ca9c772 playing White: 1 - 0 - 3  [0.625] 4
...      New-196ca9c772 playing Black: 0 - 2 - 2  [0.250] 4
...      White vs Black: 3 - 0 - 5  [0.688] 8
Elo difference: -43.7 +/- 156.7, LOS: 28.2 %, DrawRatio: 62.5 %
SPRT: llr 0 (0.0%), lbound -inf, ubound inf

Player: New-196ca9c772
"Draw by 3-fold repetition": 3
"Draw by adjudication": 2
"Loss: White wins by adjudication": 2
"Win: White wins by adjudication": 1
Player: Base-196ca9c772
"Draw by 3-fold repetition": 3
"Draw by adjudication": 2
"Loss: White wins by adjudication": 1
"Win: White wins by adjudication": 2
Finished match
Finished match cleanly
Warning: New-196ca9c772 doesn't have option AAA

Waiting for cutechess-cli to finish ... done

Exception running games:
Cutechess-cli says: "Warning: New-196ca9c772 doesn't have option AAA"
Informing the server
Error from remote: /api/stop_run: User user01 has too few games to stop a run
Post request https://dfts-0.pigazzini.it:443/api/stop_run handled in 501.33ms (server: 7.21ms)
Task exited
Waiting 15.0 seconds before retrying
```

**Comment by ppigazzini** [comment]
Confirmed, with the official `cutechess-cli` binary (and dll) the Windows worker stops immediately without playing games.

```
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 485.69ms (server: 0.13ms)
Obtaining version info for C:/tools/msys64/home/Pasquale Pigazzini/_git/__test_folder01/fishtest/worker/testing/cutechess-cli.exe ...
Found:  cutechess-cli 1.3.1
Downloading https://raw.githubusercontent.com/official-stockfish/fishtest/master/worker/sri.txt
worker.py has been modified!
games.py has been modified!
This worker is tainted...
Using g++ 13.2.0
UUID: 3d7b685c-cb6f-4317-954b-7e963d8e1414
Start heartbeat
Current time is 2023-09-25 20:21:44.380053+00:00 UTC (local offset: +02:00)
Verify worker version...
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 522.50ms (server: 0.14ms)
Remaining number of github api calls = 5000
Fetching task...
Post request https://dfts-0.pigazzini.it:443/api/request_task handled in 955.87ms (server: 453.12ms)
Working on task 38 from https://dfts-0.pigazzini.it:443/tests/view/6511e363d17ea78d961ff26d
Running new90 vs new90
Variable task sizes used. Opening offset = 4408
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
CPU factor : 1.283540003329182 - tc adjusted to 77.012+0.770
CPU factor : 1.283540003329182 - tc adjusted to 1.284+0.013
CPU factor : 1.283540003329182 - tc adjusted to 1.284+0.013
Post request https://dfts-0.pigazzini.it:443/api/request_spsa handled in 511.36ms (server: 0.28ms)
TC limit 102.68320026633455 End time: 2023-09-25 20:23:40.255279+00:00
Indexing opening suite...
Warning: New-196ca9c772 doesn't have option AAA

Waiting for cutechess-cli to finish ... done

Exception running games:
Cutechess-cli says: "Warning: New-196ca9c772 doesn't have option AAA"
Informing the server
Error from remote: /api/stop_run: User user01 has too few games to stop a run
Post request https://dfts-0.pigazzini.it:443/api/stop_run handled in 485.59ms (server: 7.49ms)
Task exited
Waiting 15.0 seconds before retrying
```

**Comment by vdbergh** [comment]
Ok. I guess cutechess-cli I/O is burried deeply inside the Qt toolkit. It seems unlikely that a simple `setbuf` somewhere would be able to fix it. But as I said, while inconvenient, the delay is not really a show stopper.

**Comment by vdbergh** [comment]
Interesting 

https://github.com/cutechess/cutechess/blob/1071d84cf272bd7deca0964336bf02e367e2b22b/projects/cli/src/main.cpp#L729-L736 

cutechess-cli does setvbuf on stdout but not on stderr. stderr is normally unbuffered, but perhaps not on windows?

**Comment by ppigazzini** [comment]
> Ok. I guess cutechess-cli I/O is burried deeply inside the Qt toolkit. It seems unlikely that a simple `setbuf` somewhere would be able to fix it. But as I said, while inconvenient, the delay is not really a show stopper.

I suspect that there is something misconfigured in the static qt5 libraries already built by msys2.

Same behavior with master as expected.
```
Fetching task...
Post request https://dfts-0.pigazzini.it:443/api/request_task handled in 536.55ms (server: 41.86ms)
Working on task 44 from https://dfts-0.pigazzini.it:443/tests/view/6511e363d17ea78d961ff26d
Running new90 vs new90
Variable task sizes used. Opening offset = 5104
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Obtaining EvalFile of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
Verifying signature of stockfish_196ca9c7726d637f07e1de54faafe002d78b55c1.exe ...
CPU factor : 1.3116232362253943 - tc adjusted to 78.697+0.787
CPU factor : 1.3116232362253943 - tc adjusted to 1.312+0.013
CPU factor : 1.3116232362253943 - tc adjusted to 1.312+0.013
Post request https://dfts-0.pigazzini.it:443/api/request_spsa handled in 492.04ms (server: 0.33ms)
TC limit 104.92985889803154 End time: 2023-09-25 20:31:28.163139+00:00
Indexing opening suite...
Started game 1 of 8 (New-196ca9c772 vs Base-196ca9c772)
Started game 2 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 2 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 1  [0.500] 1
Started game 3 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 1 (New-196ca9c772 vs Base-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 0 - 2  [0.500] 2
Started game 4 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 4 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 0 - 1 - 2  [0.333] 3
Started game 5 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 3 (New-196ca9c772 vs Base-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 1 - 1 - 2  [0.500] 4
Started game 6 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 5 (New-196ca9c772 vs Base-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 2 - 1 - 2  [0.600] 5
Started game 7 of 8 (New-196ca9c772 vs Base-196ca9c772)
Finished game 6 (Base-196ca9c772 vs New-196ca9c772): 1/2-1/2 {Draw by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 2 - 1 - 3  [0.583] 6
Started game 8 of 8 (Base-196ca9c772 vs New-196ca9c772)
Finished game 7 (New-196ca9c772 vs Base-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 3 - 1 - 3  [0.643] 7
Finished game 8 (Base-196ca9c772 vs New-196ca9c772): 1-0 {White wins by adjudication}
Score of New-196ca9c772 vs Base-196ca9c772: 3 - 2 - 3  [0.563] 8
Post request https://dfts-0.pigazzini.it:443/api/update_task handled in 753.27ms (server: 0.38ms)
...      New-196ca9c772 playing White: 3 - 0 - 1  [0.875] 4
...      New-196ca9c772 playing Black: 0 - 2 - 2  [0.250] 4
...      White vs Black: 5 - 0 - 3  [0.813] 8
Elo difference: 43.7 +/- 216.1, LOS: 67.3 %, DrawRatio: 37.5 %
Finished match
Finished match cleanly
Warning: Base-196ca9c772 doesn't have option AAA

Waiting for cutechess-cli to finish ... done

Exception running games:
Cutechess-cli says: "Warning: Base-196ca9c772 doesn't have option AAA"
Informing the server
Error from remote: /api/stop_run: User user01 has too few games to stop a run
Post request https://dfts-0.pigazzini.it:443/api/stop_run handled in 617.48ms (server: 11.31ms)
Task exited
Waiting 30.0 seconds before retrying
```

**Comment by ppigazzini** [comment]
> cutechess-cli does setvbuf on stdout but not on stderr. stderr is normally unbuffered, but perhaps not on windows?

The official binary works fine, see https://github.com/official-stockfish/fishtest/pull/1816#issuecomment-1734410588

**Review by ppigazzini — APPROVED** [review]
Looks good in my tests

**Comment by vdbergh** [comment]
> > cutechess-cli does setvbuf on stdout but not on stderr. stderr is normally unbuffered, but perhaps not on windows?
> 
> The official binary works fine, see [#1816 (comment)](https://github.com/official-stockfish/fishtest/pull/1816#issuecomment-1734410588)
> 

It may depend on the c library. stdout and stderr and their buffering are determined by the c library I think. 

Do you know the c library that the official binary is using?

**Comment by ppigazzini** [comment]
It should be this:
https://github.com/cutechess/cutechess/blob/master/.github/workflows/build.yml#L54
```yaml
            - name: build cute chess
              if: matrix.os == 'windows-latest'
              shell: cmd
              run: |
                  call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
                  mkdir build
                  cd build
                  cmake ..
                  cmake --build . --config release

```

**Comment by vdbergh** [comment]
Ok that explains it. So the official binary uses the VS c-library which presumably has a normally behaving stderr.

Perhaps stderr in msys2 is buffered by default?

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @vdbergh :)

**Comment by ppigazzini** [comment]
> Interesting
> 
> https://github.com/cutechess/cutechess/blob/1071d84cf272bd7deca0964336bf02e367e2b22b/projects/cli/src/main.cpp#L729-L736
> 
> ```
> int main(int argc, char* argv[])
> {
>         // Register types for signal / slot connections
>         qRegisterMetaType<Chess::Result>("Chess::Result");
> 
> 
>         setvbuf(stdout, nullptr, _IONBF, 0);
>         signal(SIGINT, sigintHandler);
> ```

I wrote in my todo list to try to change the code for stderr as well.

**Comment by vdbergh** [comment]
I hope this PR will also fix the mysterious "Finished match uncleanly"...  Fingers crossed.

**Comment by vdbergh** [comment]
> > Interesting
> > https://github.com/cutechess/cutechess/blob/1071d84cf272bd7deca0964336bf02e367e2b22b/projects/cli/src/main.cpp#L729-L736
> > ```
> > int main(int argc, char* argv[])
> > {
> >         // Register types for signal / slot connections
> >         qRegisterMetaType<Chess::Result>("Chess::Result");
> > 
> > 
> >         setvbuf(stdout, nullptr, _IONBF, 0);
> >         signal(SIGINT, sigintHandler);
> > ```
> 
> I wrote in my todo list to try to change the code for stderr as well.

This page https://learn.microsoft.com/en-us/cpp/c-runtime-library/stream-i-o?view=msvc-170 seems to suggest that on windows stderr is buffered ("unless connected to character device", which means a terminal I presume).

But then it would be strange that the official binary would work.

I know very little about windows. It seems that mingw-w64 has a c++ layer libstdc++ above the runtime 
 (which can be msvcrt or ucrt). I wonder if there is something like that for Visual Studio.

**Comment by vdbergh** [comment]
On the other hand, this page claims that stderr is unbuffered https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setbuf?view=msvc-170

**Pull request merged**
