### PR TITLE
Use "failed_task" api to flag a stale active task.

### PR DESCRIPTION
**Pull request by vdbergh**
This is the right thing to do in order to have an audit trail for tasks that have not played all their games.

### CODE REVIEW

**Comment by vdbergh** [comment]
Rebased.

**Comment by vondele** [comment]
If a fleet leaves, will this lead to 1000s of messages in the event log?

**Comment by vdbergh** [comment]
> If a fleet leaves, will this lead to 1000s of messages in the event log?

No because this issue only happens relatively rarely. However there are already 1000s of messages. See https://tests.stockfishchess.org/actions?action=dead_task&user=vdv&text=

Not sure if we should do something about this, and if so, what?

**Comment by vondele** [comment]
Maybe we need to reconsider if such non-error events need logging. Now, it is up to you to decide if that's a logging-worthy event, i.e. if that can be helpful.

Maybe I am a bit confused between dead task and stale active task? What's the difference?

**Comment by vdbergh** [comment]
> Maybe we need to reconsider if such non-error events need logging. Now, it is up to you to decide if that's a logging-worthy event, i.e. if that can be helpful.
> 
> Maybe I am a bit confused between dead task and stale active task? What's the difference?

A stale active task is a task whose attached worker is the same as the worker requesting a new tasks. This can happen if the worker was unable to update an old task because of server issues and gave up, i.e. requested a new task.

A dead task is a task which has not seen any updates for 6 minutes.

**Comment by vdbergh** [comment]
> Maybe we need to reconsider if such non-error events need logging. 

Well a dead task is in some sense an error since it means that the worker did not quit cleanly (e.g. with SIGINT or SIGTERM).

This being said, in the case of a fleet, quitting the worker cleanly would just replace the dead task messages by failed task messages, so they would take up a similar amount of space.

I am not sure the dead_task messages are really a problem. They would be if the actiondb starts taking up too much space. @ppigazzini can probably comment on this.

Currently the idea is that the event log logs the full life cycle of tasks and runs.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
> I am not sure the dead_task messages are really a problem. They would be if the actiondb starts taking up too much space. @ppigazzini can probably comment on this.

db.actions.totalSize() 1.031 GiB

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh

**Pull request merged**
