### PR TITLE
Workers page and icon

### PR DESCRIPTION
**Pull request by dav1312**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV update, nice :)

**Comment by vdbergh** [comment]
However it raises usual problem: does a checkbox refer to a state or to an action? For me it refers to a state (buttons are for actions). That's why I wrote "blocked" instead of "block".

**Comment by dav1312** [comment]
I just made a mistake and added the name and check to the label instead of the checkbox, that's why it doesn't work when you try to change the state, give me a minute

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by ppigazzini** [comment]
```diff
- <h2>Workers Management</h2>
+ <h2>Workers Administration</h2>
```
I used "Management" because ther was already "Worker admin"
We have "User Administration" that has the checkbox with "Blocked"
https://dfts-0.pigazzini.it/user/user01

image

**Comment by dav1312** [comment]
Okaaay I'll change it... But I like "management" and "block" more and I would much rather change it for the user page

**Comment by ppigazzini** [comment]
I'm fine with either Administration or Management, simply I would like to have consistency..

**Comment by dav1312** [comment]
Okay changed back to Management, same for the user page

**Review by ppigazzini — APPROVED** [review]
LGTM on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @dav1312 :)

**Pull request merged**
