### PR TITLE
Clean refactoring of api.py.

### PR DESCRIPTION
**Pull request by vdbergh**
This is a much better version of #1999 . Lightly tested.

The structure is now as follows
```
class GenericApi:
-- contains handle_error, add_time

class WorkerApi(GenericApi):
-- contains the apis used by the worker

class UserApi(GenericApi):
-- Apis useful for application developers

class InternalApi(GenericApi):
-- Apis (possibly exposing sensitive data) that should only be
   used by Fishtest itself (possibly access controlled).
```

### CODE REVIEW

**Comment by peregrineshahin** [comment]
Great Job!
I think some extra refactoring can be done for parts in rundb that don't belong semantically there..
Probably best would be to have a config file also for most of the urls, regexes, fixed SHAs and such.

**Comment by vdbergh** [comment]
Yes I agree we may need some kind of config file. Not sure what is the "correct" way to do this in the pyramid framework.

**Comment by ppigazzini** [comment]
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html#adding-a-custom-setting

**Comment by peregrineshahin** [comment]
> Yes I agree we may need some kind of config file. Not sure what is the "correct" way to do this in the pyramid framework.

I wouldn't consider such configs enviroment-specific, in my projects I create my own `config.json` for actual hardcoded data and import it in my desired files. probably not that trivial with python or there is easier ways with such framework.

**Comment by ppigazzini** [comment]
The standard Pyramid's configuration files are `development.ini` and `configuration.ini`.
We build other configuration objects (like the `cache_busters`) in `__init__.py`

**Comment by vdbergh** [comment]
Of course Python can work with config files (e.g. the worker). But pyramid already has its own configuration framework. It would perhaps be useful to understand that first.

**Comment by ppigazzini** [comment]
Some information (secrets, tokens, reserved URL) must be or read from an external file or passed as environment variable. At the moment we are using both the ways.

**Comment by vdbergh** [comment]
IUC then according to 

https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html#adding-a-custom-setting

any custom settings can be added to `[app:main]` in the ini file (currently `development.ini` or `production.ini`).

It seems to me that we could do this for the HTTP port (via the `http_port` variable) so what we do not have to resort the hacky method currently used for determining it within Fishtest.

**Comment by ppigazzini** [comment]
```diff
diff --git a/server/fishtest/api.py b/server/fishtest/api.py
index 3c8a18e..73579ab 100644
--- a/server/fishtest/api.py
+++ b/server/fishtest/api.py
@@ -378,6 +378,9 @@ class UserApi(GenericApi):

     @view_config(route_name="api_actions")
     def actions(self):
+        settings = self.request.registry.settings
+        secret = settings["myapp.secret"]
+        print(secret, flush=True)
         try:
             query = self.request.json_body
             actions = self.request.rundb.db["actions"].find(query).limit(200)
diff --git a/server/production.ini b/server/production.ini
index badc7cc..ef66d90 100644
--- a/server/production.ini
+++ b/server/production.ini
@@ -14,6 +14,8 @@ pyramid.default_locale_name = en

 mako.directories = fishtest:templates

+myapp.secret = "some_secret_key"
+
 ###
 # wsgi server configuration
 ###
```

```yaml
sudo journalctl -u fishtest@6545 --since "5 minutes ago"
-- Logs begin at Sat 2024-05-11 18:16:10 CEST, end at Sat 2024-05-11 18:17:23 CEST. --
May 11 18:16:15 dfts-0 pserve[23580]: "some_secret_key"
May 11 18:16:40 dfts-0 pserve[23580]: "some_secret_key"
May 11 18:17:02 dfts-0 pserve[23580]: "some_secret_key"


```

**Comment by ppigazzini** [comment]
some experiments, perhaps can be is useful:
```diff
diff --git a/server/fishtest/__init__.py b/server/fishtest/__init__.py
index 028c349..8efc3a7 100644
--- a/server/fishtest/__init__.py
+++ b/server/fishtest/__init__.py
@@ -10,6 +10,7 @@ from pyramid.events import BeforeRender, NewRequest
 from pyramid.httpexceptions import HTTPFound
 from pyramid.security import forget
 from pyramid.session import SignedCookieSessionFactory
+from pyramid.settings import asbool, aslist

 from fishtest import helpers

@@ -43,6 +44,24 @@ def main(global_config, **settings):

     rundb = RunDb()

+    def parse_dict(value):
+        return dict(item.split(":") for item in aslist(value))
+
+    my_string = settings["myapp.my_string"]
+    my_int = int(settings["myapp.my_int"])
+    my_bool_0 = asbool(settings["myapp.my_bool_0"])
+    my_bool_1 = asbool(settings["myapp.my_bool_1"])
+    my_bool_2 = asbool(settings["myapp.my_bool_2"])
+    my_list = aslist(settings["myapp.my_list"])
+    my_dict = parse_dict(settings["myapp.my_dict"])
+    print(f"{my_string=}", flush=True)
+    print(f"{my_int=}", flush=True)
+    print(f"{my_bool_0=}", flush=True)
+    print(f"{my_bool_1=}", flush=True)
+    print(f"{my_bool_2=}", flush=True)
+    print(f"{my_list=}", flush=True)
+    print(f"{my_dict=}", flush=True)
+
     def add_rundb(event):
         event.request.rundb = rundb
         event.request.userdb = rundb.userdb
diff --git a/server/production.ini b/server/production.ini
index badc7cc..9f41189 100644
--- a/server/production.ini
+++ b/server/production.ini
@@ -14,6 +14,15 @@ pyramid.default_locale_name = en

 mako.directories = fishtest:templates

+myapp.my_string = hello
+myapp.my_int = 123
+myapp.my_bool_0 = true
+myapp.my_bool_1 = True
+myapp.my_bool_2 = 1
+myapp.my_list = item1, item2, item3
+myapp.my_dict = key0:value0, key1:value1
+
+
 ###
 # wsgi server configuration
 ###
```


```yaml
usr00@dfts-0:~/fishtest/server$ sudo journalctl -u fishtest@6543 --since "5 minutes ago"
-- Logs begin at Sat 2024-05-11 18:58:45 CEST, end at Sat 2024-05-11 18:59:09 CEST. --
May 11 18:59:01 dfts-0 systemd[1]: Started Fishtest Server port 6543.
May 11 18:59:02 dfts-0 pserve[27111]: my_string='hello'
May 11 18:59:02 dfts-0 pserve[27111]: my_int=123
May 11 18:59:02 dfts-0 pserve[27111]: my_bool_0=True
May 11 18:59:02 dfts-0 pserve[27111]: my_bool_1=True
May 11 18:59:02 dfts-0 pserve[27111]: my_bool_2=True
May 11 18:59:02 dfts-0 pserve[27111]: my_list=['item1,', 'item2,', 'item3']
May 11 18:59:02 dfts-0 pserve[27111]: my_dict={'key0': 'value0,', 'key1': 'value1'}
May 11 18:59:03 dfts-0 pserve[27111]: Starting server in PID 27111.
```

**Comment by vdbergh** [comment]
Perhaps instead of `parse_dict` one can just use `json.loads`. This then also works for more complicated data structures.

In #2001 I use `port` and `primary_port`. Should we use `fishstest.port` and `fishstest.primary_port` instead?

**Comment by vdbergh** [comment]
Ah I misunderstood. The dictionary is not written in json but as `key0:value0, key1:value1`.

I sort of assumed we would be using json for the options.

**Comment by ppigazzini** [comment]
loading a complex dict with `json`

```diff
diff --git a/server/fishtest/__init__.py b/server/fishtest/__init__.py
index 028c349..befc30b 100644
--- a/server/fishtest/__init__.py
+++ b/server/fishtest/__init__.py
@@ -1,5 +1,6 @@
 import base64
 import hashlib
+import json
 from pathlib import Path

 from fishtest.rundb import RunDb
@@ -10,6 +11,7 @@ from pyramid.events import BeforeRender, NewRequest
 from pyramid.httpexceptions import HTTPFound
 from pyramid.security import forget
 from pyramid.session import SignedCookieSessionFactory
+from pyramid.settings import asbool, aslist

 from fishtest import helpers

@@ -43,6 +45,21 @@ def main(global_config, **settings):

     rundb = RunDb()

+    my_string = settings["myapp.my_string"]
+    my_int = int(settings["myapp.my_int"])
+    my_bool_0 = asbool(settings["myapp.my_bool_0"])
+    my_bool_1 = asbool(settings["myapp.my_bool_1"])
+    my_bool_2 = asbool(settings["myapp.my_bool_2"])
+    my_list = aslist(settings["myapp.my_list"])
+    my_dict = json.loads(settings["myapp.my_dict"])
+    print(f"{my_string=}", flush=True)
+    print(f"{my_int=}", flush=True)
+    print(f"{my_bool_0=}", flush=True)
+    print(f"{my_bool_1=}", flush=True)
+    print(f"{my_bool_2=}", flush=True)
+    print(f"{my_list=}", flush=True)
+    print(f"{my_dict=}", flush=True)
+
     def add_rundb(event):
         event.request.rundb = rundb
         event.request.userdb = rundb.userdb
diff --git a/server/production.ini b/server/production.ini
index badc7cc..ae030e7 100644
--- a/server/production.ini
+++ b/server/production.ini
@@ -14,6 +14,15 @@ pyramid.default_locale_name = en

 mako.directories = fishtest:templates

+myapp.my_string = hello
+myapp.my_int = 123
+myapp.my_bool_0 = true
+myapp.my_bool_1 = True
+myapp.my_bool_2 = 1
+myapp.my_list = item1, item2, item3
+myapp.my_dict = {"key1": {"subkey1": "value1", "subkey2": [1, 2, 3]}, "key2": ["item1", "item2", "item3"], "key3": true}
+
+
 ###
 # wsgi server configuration
 ###
```

```yaml
usr00@dfts-0:~/fishtest/server$ sudo journalctl -u fishtest@6543 --since "5 minutes ago"
-- Logs begin at Sat 2024-05-11 19:07:08 CEST, end at Sat 2024-05-11 19:14:44 CEST. --
May 11 19:09:52 dfts-0 pserve[28181]: Stale active task detected for worker "user01-2cores-00f99de7-29ef*". Correcting...
May 11 19:10:35 dfts-0 pserve[28181]: flush
May 11 19:10:35 dfts-0 pserve[28181]: done
May 11 19:10:35 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
May 11 19:10:36 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
May 11 19:14:41 dfts-0 systemd[1]: Started Fishtest Server port 6543.
May 11 19:14:42 dfts-0 pserve[28356]: my_string='hello'
May 11 19:14:42 dfts-0 pserve[28356]: my_int=123
May 11 19:14:42 dfts-0 pserve[28356]: my_bool_0=True
May 11 19:14:42 dfts-0 pserve[28356]: my_bool_1=True
May 11 19:14:42 dfts-0 pserve[28356]: my_bool_2=True
May 11 19:14:42 dfts-0 pserve[28356]: my_list=['item1,', 'item2,', 'item3']
May 11 19:14:42 dfts-0 pserve[28356]: my_dict={'key1': {'subkey1': 'value1', 'subkey2': [1, 2, 3]}, 'key2': ['item1', 'item2', 'item3'], 'key3': True}
May 11 19:14:42 dfts-0 pserve[28356]: Starting server in PID 28356.
```

**Comment by ppigazzini** [comment]
> In #2001 I use `port` and `primary_port`. Should we use `fishstest.port` and `fishstest.primary_port` instead?

Yes, it's better!

**Comment by ppigazzini** [comment]
> In #2001 I use `port` and `primary_port`. Should we use `fishstest.port` and `fishstest.primary_port` instead?

Yes, or json perhaps.

**Comment by vdbergh** [comment]
I don't understand. I don't see the role of json when having to communicate two numbers.
In #2001  `[app:main]` contains
```
fishtest.port = %(http_port)s
fishtest.primary_port = 6543
```

**Comment by peregrineshahin** [comment]
btw what I meant also regarding RunDb class is that it has the cache code related to runs, and not only the database related method, if that was refactored I see a huge improvement, if we can very easily differantiate..

**Comment by ppigazzini** [comment]
> fishtest.port = %(http_port)s
> fishtest.primary_port = 6543

In case we want to have only one dict with the ports.

```diff
diff --git a/server/production.ini b/server/production.ini
index badc7cc..04f6433 100644
--- a/server/production.ini
+++ b/server/production.ini
@@ -14,6 +14,16 @@ pyramid.default_locale_name = en

 mako.directories = fishtest:templates

+myapp.my_string = hello
+myapp.my_int = 123
+myapp.my_bool_0 = true
+myapp.my_bool_1 = True
+myapp.my_bool_2 = 1
+myapp.my_list = item1, item2, item3
+myapp.my_dict = {"key1": {"subkey1": "value1", "subkey2": [1, 2, 3]}, "key2": ["item1", "item2", "item3"], "key3": true}
+fishtest.ports = {"port": %(http_port)s, "primary": 6543}
```


```yaml
usr00@dfts-0:~/fishtest/server$ sudo journalctl -u fishtest@6544 --since "5 minutes ago"
-- Logs begin at Sat 2024-05-11 19:48:06 CEST, end at Sat 2024-05-11 19:48:36 CEST. --
May 11 19:48:19 dfts-0 systemd[1]: Started Fishtest Server port 6544.
May 11 19:48:20 dfts-0 pserve[30502]: my_string='hello'
May 11 19:48:20 dfts-0 pserve[30502]: my_int=123
May 11 19:48:20 dfts-0 pserve[30502]: my_bool_0=True
May 11 19:48:20 dfts-0 pserve[30502]: my_bool_1=True
May 11 19:48:20 dfts-0 pserve[30502]: my_bool_2=True
May 11 19:48:20 dfts-0 pserve[30502]: my_list=['item1,', 'item2,', 'item3']
May 11 19:48:20 dfts-0 pserve[30502]: my_dict={'key1': {'subkey1': 'value1', 'subkey2': [1, 2, 3]}, 'key2': ['item1', 'item2', 'item3'], 'key3': True}
May 11 19:48:20 dfts-0 pserve[30502]: fishtest_ports={'port': 6544, 'primary': 6543}
May 11 19:48:20 dfts-0 pserve[30502]: Starting server in PID 30502.
```

**Comment by vdbergh** [comment]
Hmm... I guess it depends on taste but this seems a bit overkill to me.

**Comment by ppigazzini** [comment]
IMO we should be able to read the port in the server section without duplication of the data. Dinner time now!

```ini
[server:main]
use = egg:waitress#main
host = 127.0.0.1
port = %(http_port)s

```

**Comment by peregrineshahin** [comment]
> Dinner time now!
My Shawarma delivery is taking ages :P (JK I've just ordered)...

**Comment by ppigazzini** [comment]
> > Dinner time now!
> 
> My Shawarma delivery is taking ages :P (JK I've just ordered)...

Delivery?!? 20 minutes recipe.
Toast 40g of rice in a sauté of extra virgin olive oil and cut shallots and garlic, then add half a glass of white wine, then broth and 140g of fresh peas.
When cooked, add half teaspoon of Dijon mustard and two pieces of Parmigiano Reggiano cheese.

**Comment by ppigazzini** [comment]
> This is what master does (it parses the arguments of the invoking pserve to get the name of the config file and the arguments and then it parses the config file to get the value of `port`). But I find that very ugly.

Yes, pyramid get only the `[app:main]` section.

**Review by ppigazzini — APPROVED** [review]
Looks good with DEV+workers

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh

**Pull request merged**
