### PR TITLE
Generate a "pending" accept_user event on signup.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by vdbergh** [comment]
Hmm maybe not a good idea. People could register with an offensive username which would then be visible for everyone in the event log.

**Comment by vdbergh** [comment]
Since I don't see a good solution to this issue I am closing this PR for now.

**Comment by vdbergh** [comment]
It seems that the current system already has this problem. If someone registers with an offensive username then, if I understand correctly, the only way to keep that name out of the event log is to keep the user pending forever, which is not desirable.

I am reopening this to have some debate.

**Comment by peregrineshahin** [comment]
That's right. I will make two buttons instead of the checkboxes, one is with Accept and one is with Reject
Not doing anything will keep the user pending
Accept will accept the user
Reject will remove them from the database.

**Comment by vdbergh** [comment]
Closing this again in view of #1859

**Pull request closed without merging**
