### PR TITLE
Make it possible to send an email from worker management.

### PR DESCRIPTION
**Pull request by vdbergh**
Sending an email is independent of blocking/unblocking as blocking is really only necessary in case a worker generates excessive time losses.

The actual sending of email was not really tested since I do not run an smtp server on localhost.

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated

**Comment by ppigazzini** [comment]
It doesn't work.
I expected CloudFlare to be configured to strictly control the SMTP relay:
https://developers.cloudflare.com/dmarc-management/security-records/

Same for the receiver DNS.

**Comment by vdbergh** [comment]
Hmmm

**Comment by vdbergh** [comment]
Does this mean that posting to Fishcooking also does not work?

**Comment by ppigazzini** [comment]
Prosign to Fishcooking works because Google has unexpectedly configured the DNS in lazy way.
I configured PROD with the same Fisckcooking sender email, no result.

```
Sep 09 10:50:57 tests.stockfishchess.org pserve[24718]: Sending email to p****e.p****i@gmail.com from fishtest@noreply.stockfishchess.org: Block the worker to test the send mail function, see https://github.com/official-stockfish/fi
Sep 09 10:50:57 tests.stockfishchess.org pserve[24718]: Attempt n. 2
```

**Comment by vdbergh** [comment]
I assume the main issue with this PR is that we cannot freely set the From address. 

If stockfish had a gmail address then we could use this as From address and then we could use the Google smtp server (that's how I tested this PR).

**Comment by ppigazzini** [comment]
Yes, this is why I set the sender email to "fishtest@noreply.stockfishchess.org"
But something stopped working in August, 16 2023.

By the way I'm not a fan of this PR:
- we have not direct control on DNS setting
- the user is only a step away (open the email client) 
- the message is intended for the worker and should be short and technical
- I always write a friendly email to the contributor when asking to check the worker

**Comment by vdbergh** [comment]
Using the Google smtp server definitely works if you have a gmail account (you have to generate an app password).

I made an attempt to make the actual email friendly (perhaps that was not clear). But if the From address cannot be the email address of the blocker (even if the From address is a real email address such as stockfish@gmail.com with a person behind it) then that creates indeed serious problems for following up any issues....

**Comment by ppigazzini** [comment]
The DNS of stockfishchess.org is not configured to have PROD as SMTP relay, the Fishcooking group was mis configured. 
```bash
$ (echo "From: fishtest@noreply.stockfishchess.org"; echo "Subject: Test Email"; echo ""; echo "This is a test email.") | exim -v -odf p***.p***@gmail.com
LOG: MAIN
  <= fishtest@tests.stockfishchess.org U=fishtest P=local S=398
delivering 1qexSa-0000RY-SW
R: dnslookup for p***.p***@gmail.com
T: remote_smtp for p***.p***@gmail.com
Connecting to gmail-smtp-in.l.google.com [2a00:1450:4025:401::1b]:25 ... failed: Network is unreachable
LOG: MAIN
  H=gmail-smtp-in.l.google.com [2a00:1450:4025:401::1b] Network is unreachable
Connecting to gmail-smtp-in.l.google.com [142.250.27.26]:25 ... connected
  SMTP<< 220 mx.google.com ESMTP la17-20020a170906ad9100b00992b75d594csi3431790ejb.317 - gsmtp
  SMTP>> EHLO tests.stockfishchess.org
  SMTP<< 250-mx.google.com at your service, [185.83.217.134]
         250-SIZE 157286400
         250-8BITMIME
         250-STARTTLS
         250-ENHANCEDSTATUSCODES
         250-PIPELINING
         250-CHUNKING
         250 SMTPUTF8
  SMTP>> STARTTLS
  SMTP<< 220 2.0.0 Ready to start TLS
  SMTP>> EHLO tests.stockfishchess.org
  SMTP<< 250-mx.google.com at your service, [185.83.217.134]
         250-SIZE 157286400
         250-8BITMIME
         250-ENHANCEDSTATUSCODES
         250-PIPELINING
         250-CHUNKING
         250 SMTPUTF8
  SMTP>> MAIL FROM:<fishtest@tests.stockfishchess.org> SIZE=1431
  SMTP>> RCPT TO:<p***.p***@gmail.com>
         will write message using CHUNKING
  SMTP>> BDAT 408 LAST
  SMTP<< 250 2.1.0 OK la17-20020a170906ad9100b00992b75d594csi3431790ejb.317 - gsmtp
  SMTP<< 250 2.1.5 OK la17-20020a170906ad9100b00992b75d594csi3431790ejb.317 - gsmtp
  SMTP<< 550-5.7.26 This mail is unauthenticated, which poses a security risk to the
         550-5.7.26 sender and Gmail users, and has been blocked. The sender must
         550-5.7.26 authenticate with at least one of SPF or DKIM. For this message,
         550-5.7.26 DKIM checks did not pass and SPF check for [tests.stockfishchess.org
         550-5.7.26 ] did not pass with ip: [185.83.217.134]. The sender should visit
         550-5.7.26  https://support.google.com/mail/answer/81126#authentication for
         550 5.7.26 instructions on setting up authentication. la17-20020a170906ad9100b00992b75d594csi3431790ejb.317 - gsmtp
  SMTP>> QUIT
  SMTP(close)>>
LOG: MAIN
  ** p***.p***@gmail.com R=dnslookup T=remote_smtp H=gmail-smtp-in.l.google.com [142.250.27.26] X=TLS1.2:ECDHE_ECDSA_CHACHA20_POLY1305:256 CV=yes DN="CN=mx.google.com": SMTP error from remote mail server after pipelined end of data: 550-5.7.26 This mail is unauthenticated, which poses a security risk to the\n550-5.7.26 sender and Gmail users, and has been blocked. The sender must\n550-5.7.26 authenticate with at least one of SPF or DKIM. For this message,\n550-5.7.26 DKIM checks did not pass and SPF check for [tests.stockfishchess.org\n550-5.7.26 ] did not pass with ip: [185.83.217.134]. The sender should visit\n550-5.7.26  https://support.google.com/mail/answer/81126#authentication for\n550 5.7.26 instructions on setting up authentication. la17-20020a170906ad9100b00992b75d594csi3431790ejb.317 - gsmtp
LOG: MAIN
  <= <> R=1qexSa-0000RY-SW U=Debian-exim P=local S=3057
delivering 1qexSb-0000Rc-IH
R: system_aliases for fishtest@tests.stockfishchess.org
R: userforward for fishtest@tests.stockfishchess.org
R: procmail for fishtest@tests.stockfishchess.org
R: maildrop for fishtest@tests.stockfishchess.org
R: lowuid_aliases for fishtest@tests.stockfishchess.org (UID 1000)
R: local_user for fishtest@tests.stockfishchess.org
T: appendfile for fishtest@tests.stockfishchess.org
LOG: MAIN
  => fishtest <fishtest@tests.stockfishchess.org> R=local_user T=mail_spool
LOG: MAIN
  Completed
LOG: MAIN
  Completed
You have new mail in /var/mail/fishtest
```

**Comment by vdbergh** [comment]
As I understand it you have to enable the use of fishtest@noreply.stockfishchess.org as a secondary From address in your gmail account if you want the Google smtp server to preserve the From address. I did this and it worked.

**Comment by ppigazzini** [comment]
This has been a standard for years now, to limit spam and mail abuse.
https://www.cloudflare.com/learning/email-security/dmarc-dkim-spf/
I was amazed that the email to the Fishcooking group worked without a proper DNS setting (shame on Google).

**Pull request closed without merging**
