### PR TITLE
Document the format of the cache in schemas.py.

### PR DESCRIPTION
**Pull request by vdbergh**
Requires upgrade of vtjson.

### CODE REVIEW

**Comment by vdbergh** [comment]
Note that the schema is slightly convoluted since vtjson currently cannot handle dicts whose keys are themselves schemas.
```python
cache_schema = intersect(
    dict,
    filter(
        lambda x: list(x.items()),
        [
            (
                run_id,
                {
                    "run": runs_schema,
                    "dirty": bool,  # Indicates if the run has changed since last write to db.
                    "ftime": ufloat,  # Creation time of entry if dirty==False, else last sync (reading or writing from db)
                    "rtime": ufloat,  # Last time the cache entry was touched (via buffer() or get_run()).
                    "scavenge?": ufloat,  # Last time the run was scavenged for dead tasks.
                },
            ),
            ...,
        ],
        filter_name="items",
    ),
)
```

**Comment by vdbergh** [comment]
This is the schema
```python
cache_schema = {
    run_id: {
        "run": runs_schema,
        "dirty": bool,  # Indicates if the run has changed since last write to db.
        "ftime": ufloat,  # Last sync time (reading from or writing to db). If never synced then creation time.
        "rtime": ufloat,  # Last time the cache entry was touched (via buffer() or get_run()).
        "scavenge?": ufloat,  # Last time the run was scavenged for dead tasks.
    },
}
```

**Comment by ppigazzini** [comment]
These names are used only in few lines of `rundb.py`, I wonder if we can replace with more standard/descriptive names, eg
```python
cache_schema = {
    run_id: {
        "run": runs_schema
        "is_modified": bool,  # Indicates if the run has changed since last write to db.
        "last_sync_time": ufloat,  # Last sync time (reading from or writing to db). If never synced then creation time.
        "last_access_time": ufloat,  # Last time the cache entry was touched (via buffer() or get_run()).
        "last_scavenge_time": ufloat,  # Last time the run was scavenged for dead tasks.
    },
}
```


```bash
$ git grep -n dirty
server/fishtest/rundb.py:375:                        "dirty": False,
server/fishtest/rundb.py:404:                    "dirty": False,
server/fishtest/rundb.py:417:                    "dirty": True,
server/fishtest/rundb.py:435:            if entry is not None and entry["dirty"]:
server/fishtest/rundb.py:449:                if not self.run_cache[r_id]["dirty"]:
server/fishtest/rundb.py:469:                self.run_cache[oldest]["dirty"] = False


$ git grep -n ftime
server/fishtest/rundb.py:373:                        "ftime": time.time(),
server/fishtest/rundb.py:406:                    "ftime": time.time(),
server/fishtest/rundb.py:413:                    ftime = self.run_cache[r_id]["ftime"]
server/fishtest/rundb.py:415:                    ftime = time.time()
server/fishtest/rundb.py:419:                    "ftime": ftime,
server/fishtest/rundb.py:462:                elif self.run_cache[r_id]["ftime"] < old:
server/fishtest/rundb.py:463:                    old = self.run_cache[r_id]["ftime"]
server/fishtest/rundb.py:470:                self.run_cache[oldest]["ftime"] = time.time()


$ git grep -n rtime
server/fishtest/rundb.py:367:                    self.run_cache[r_id]["rtime"] = time.time()
server/fishtest/rundb.py:372:                        "rtime": time.time(),
server/fishtest/rundb.py:405:                    "rtime": time.time(),
server/fishtest/rundb.py:418:                    "rtime": time.time(),
server/fishtest/rundb.py:460:                    if self.run_cache[r_id]["rtime"] < now - 300:


$ git grep -n scavenge
server/fishtest/rundb.py:451:                        "scavenge" not in self.run_cache[r_id]
server/fishtest/rundb.py:452:                        or self.run_cache[r_id]["scavenge"] < now - 60
server/fishtest/rundb.py:454:                        self.run_cache[r_id]["scavenge"] = now
server/fishtest/rundb.py:455:                        if self.scavenge(self.run_cache[r_id]["run"]):
server/fishtest/rundb.py:467:                self.scavenge(self.run_cache[oldest]["run"])
server/fishtest/rundb.py:468:                self.run_cache[oldest]["scavenge"] = now
server/fishtest/rundb.py:483:    def scavenge(self, run):
server/fishtest/rundb.py:486:        # print("scavenge ", run["_id"])
```

**Comment by vdbergh** [comment]
I agree. I will make a new version later.

**Comment by vdbergh** [comment]
Changed. I hope I did not mess up.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV and with `git grep`

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh

**Pull request merged**
