### PR TITLE
Allow a user to delete their own account

### PR DESCRIPTION
**Pull request by peregrineshahin**
image

### CODE REVIEW

**Comment by vdbergh** [comment]
How about flagging the account as deleted, instead of deleting it from the database?

**Comment by peregrineshahin** [comment]
> How about flagging the account as deleted, instead of deleting it from the database?

Tests will not be deleted and shall be accessible with links as they are not user-url-encoded, although the test page of the user will not show their tests as it will give 404 after clicking their tests link from a test which is fine I think.
Removing the user from the database in case they wanted so, keeps the integrety of the website and is by today's standard not just security but also related to legal ramifications from GDPR and similar laws.

**Comment by ddobbelaere** [comment]
After the account is deleted, is it still possible (e.g. by somebody else) to reregister the same account name? 

If so, this certainly does not feel right to me and means that there should be at least a list if past account names kept. But you might as well "flag" the account as deleted then (along with removing all possible personal data except the user name).

**Comment by peregrineshahin** [comment]
> After the account is deleted, is it still possible (e.g. by somebody else) to reregister the same account name?
> 
> If so, this certainly does not feel right to me and means that there should be at least a list of past account names kept. But you might as well "flag" the account as deleted then (along with removing all possible personal data except the user name), as @vdbergh alludes to.

That's not the only way to prevent impersonation, we can check for registeration on demand if there was any action related such username before.

**Comment by vondele** [comment]
some comments here that come to my mind... nothing definitive.

* I do think we need to keep a trace of that user in the DB. The user handle is part of the logs / tests etc.
* There need to be a mechanism to prevent misuse, e.g. create account, spam, delete account is probably not ideal. So, like we do for creation, I think it makes sense to require approval for deletion.
* I think rather than deleting the user, I think removing user data associated with that field is the way to go (which I think is just the email, maybe the real name is provided as well).
* We do need to make sure the user handle can't be recycled.

**Pull request closed without merging**
