### PR TITLE
Simplify page redirection after required login

### PR DESCRIPTION
**Pull request by ppigazzini**

### CODE REVIEW

**Comment by vdbergh** [comment]
Would it be a good idea to do this login redirection by default?

**Comment by peregrineshahin** [comment]
> Would it be a good idea to do this login redirection by default?
not sure what that means?

redirecting to login even if the user is logged in and then redirect back to the page? no

**Comment by ppigazzini** [comment]
This https://github.com/official-stockfish/fishtest/pull/1778 has hidden nearly all the buttons not usable if not logged in, the redirection works mostly when having several tabs open with the buttons shown, logout in one tab, press on a button (new run, net upload, user management, worker management etc.) in another tab.

**Comment by peregrineshahin** [comment]
Why removed this btw?
this was intended for reschedule.......

**Comment by vdbergh** [comment]
> > Would it be a good idea to do this login redirection by default?
> 
> not sure what that means?
> 
> redirecting to login even if the user is logged in and then redirect back to the page? no

No just using a wrapper around request.login that sends you automatically to request.path after login (this functionality is used in several places now).

**Comment by peregrineshahin** [comment]
I think this simplification is incorrect because it was dealing with recheduling when you are not logged in.

**Comment by peregrineshahin** [comment]
i.e. click reschedule when you are not logged in -> takes you to login -> login -> the test run is now empty as opposed to being filled and ready for reschedule

**Comment by vdbergh** [comment]
Perhaps path_qs works? https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.path_qs

**Comment by peregrineshahin** [comment]
> Perhaps path_qs works? https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.path_qs

That's very interesting one.

**Comment by peregrineshahin** [comment]
> Perhaps path_qs works? https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.path_qs

perfect finding indeed! just what we wants.

**Pull request merged**
