### PR TITLE
Fix for #2060.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
PROD running with the PR.

**Comment by vdbergh** [comment]
Purging this run give an exception https://tests.stockfishchess.org/tests/view/666073c7c340c8eed7757c30?show_task=26

**Comment by vdbergh** [comment]
Should be fixed (missing "self.").

**Comment by ppigazzini** [comment]
PROD updated, I added #2059 as well.

**Comment by vdbergh** [comment]
Unfortunately the exception purging  https://tests.stockfishchess.org/tests/view/666073c7c340c8eed7757c30?show_task=26 persists :( Can you have a look in the log?

**Comment by vdbergh** [comment]
Found it and fixed it. Coding without testing is really not for me.

**Comment by ppigazzini** [comment]
PROD updated.

**Comment by ppigazzini** [comment]
Logs are clean.

**Pull request merged**
