### PR TITLE
Wrap worker block message.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated

**Comment by vdbergh** [comment]
I slightly reformatted the message

**Comment by ppigazzini** [comment]
DEV updated. I will be away from the keyboard for a couple fo hours.

**Review by ppigazzini — APPROVED** [review]
LGTM on DEV and workers

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
