### PR TITLE
Assorted cleanup.

### PR DESCRIPTION
**Pull request by peregrineshahin**
All functionalities touched should be Dev-tested, but this cleanup is essential and probably had to be done at some point (making the maintainer's life harder).

### CODE REVIEW

**Comment by peregrineshahin** [comment]
My VS code prettier extension does not format like the prettier fishtest got from NPM, and this laptop doesn't have npm.
So a prettier run will be appreciated.

**Comment by ppigazzini** [comment]
Formatted, force pushed, DEV updated.

**Comment by ppigazzini** [comment]
DEV updated with https://github.com/official-stockfish/fishtest/commit/0437c267b12a1904bc2a1d91e402340d43977566

**Comment by ppigazzini** [comment]
DEV updated to https://github.com/official-stockfish/fishtest/commit/46e665f234796c3715e65df5919086c0aeaeaa5b

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/2c0a9785cced47d13c7729c0309c2b6c7b38d803

**Comment by peregrineshahin** [comment]
I fixed the bugs I see.. not sure there is anything left..

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/eb2947c0245624be573b952cfe3260352947d1d5

**Comment by peregrineshahin** [comment]
> DEV with [eb2947c](https://github.com/official-stockfish/fishtest/commit/eb2947c0245624be573b952cfe3260352947d1d5)

LGTM

**Comment by peregrineshahin** [comment]
I messed up, the formatter again. please format :P

**Comment by peregrineshahin** [comment]
> I messed up, the formatter again. please format :P

Never mind I fixed it manually

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/caa6e7552d85b3b378286da8280a76184f00ab11

**Comment by peregrineshahin** [comment]
HTML inside the mako templates has been formatted using https://prettier.io/playground/

**Comment by peregrineshahin** [comment]
Something I find ugly, some code is camelCase and some code is snake_case in JS, that's due to me writing camelCase and vdbergh writing snake_case.. I do follow snake_case in python but I really find it very unnatural to use in JS..

**Comment by peregrineshahin** [comment]
Take this as an example
`document.getElementById(something)`

The language itself is written with camelCase...

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/691a2f95da0528c4b1a57d1d8203defd324566f5

Are you really offering to change all JS to proper camelCase?

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/aca902c6fd58c8226fc72b96b62596b2016adea4

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/ead5efd86c319fe9a5bd99ccf6301bf461b0251c

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/704300451db54adba3a9ff14f808c4c22b225f36

**Comment by peregrineshahin** [comment]
Now for this function I suspect some more keys got stale?
I guess we will need to wait for vdbergh to add the key if something got stale after the camelCase swtich, but still should be no issue, users should cleanup their local storages and cookies already from time to time :P
```
function cleanup_() {
  // Remove stale local storage items.
  localStorage.removeItem("fishtest_disable_notification");
  localStorage.removeItem("fishtest_notifications");
  localStorage.removeItem("fishtest_notifications_v2");
  localStorage.removeItem("fishtest_timestamp");
  localStorage.removeItem("fishtest_timestamp_purge");
}
```

**Comment by ppigazzini** [comment]
We could remove temporary both snake-camel in cleanup and drop the snake in the future (eg in 2 months). A comment could reminder the future drop.

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/e55e2138753d243590f28f2f6cfc4c8b188e6bf4

**Comment by ppigazzini** [comment]
It's broken
https://dfts-0.pigazzini.it/sprt_calc

**Comment by peregrineshahin** [comment]
The fail is a false positive as this happened exactly at the same time with SF repo merging

**Comment by ppigazzini** [comment]
DEV with https://github.com/official-stockfish/fishtest/commit/8b9ed50a418bcb2a5fdb0531c13f1f3d69223f15

**Comment by ppigazzini** [comment]
> The fail is a false positive as this happened exactly at the same time with SF repo merging

On DEV (with the PR code) that test is working fine. I don't know why it keeps failing in the CI.

**Comment by peregrineshahin** [comment]
Are you sure you triggered the CI again?
```
test (3.11)
failed 15 minutes ago in 47s
```

**Comment by ppigazzini** [comment]
image

**Comment by Disservin** [comment]
Fails because stockfish bench now has 6 digits.

https://github.com/official-stockfish/fishtest/blob/master/server/tests/test_run.py#L13

**Review by ppigazzini — APPROVED** [review]
Tested for weeks on DEV, it seems that all the bugs are iron out, today I fixed only a typo in a mako template.

**Comment by ppigazzini** [comment]
PROD updated.

**Pull request merged**
