### PR TITLE
Show more info about user and in profile

### PR DESCRIPTION
**Pull request by peregrineshahin**
shows tests repo and the groups the user belong to

### CODE REVIEW

**Comment by peregrineshahin** [comment]
drafting this, since I think registered users should input their GitHub test repo and should be able to change it as discussed before with @vdbergh. will implement that probably today or tomorrow.
it gives also a better anti spam user-regestriation..

**Comment by vondele** [comment]
A bit related, having a separate page (visible only to approvers) with a list of all approvers and their last active date would be useful at times.

**Comment by peregrineshahin** [comment]
> A bit related, having a separate page (visible only to approvers) with a list of all approvers and their last active date would be useful at times.

Yes this would be a nice feature, I think we should know who are other approvers.
that's easily doable, but I think the 'last active' is not available at first glance that, I think we only track 'last active' for users by their worker activity, we probably should also do that for (test submision/test approval/modification) now not sure if we do it.

**Comment by vondele** [comment]
you are probably right we don't have that, other than via a search in the actions database, at least now approvals are being tracked.

**Comment by vondele** [comment]
note that people that contribute resources (cpu time) might not have a github repo, and might be confused about why this is needed? If we add that, consider clarifying that this is only useful for contributors that want to code software.

**Comment by peregrineshahin** [comment]
undrafted, looks good to me on local instance.

Capture3
Capture
Capture2

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin

**Pull request merged**
