### PR TITLE
Use active_run_lock(run) to protect updates of aggregated data.

### PR DESCRIPTION
**Pull request by vdbergh**
We changed the active_run_locks to be reentrant.

### CODE REVIEW

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by vdbergh** [comment]
@ppigazzini Can you check in the server log if there are messages like this
https://github.com/official-stockfish/fishtest/blob/a51582a974c960ceef2695da345d07c461aa2b33/server/fishtest/rundb.py#L1202-L1209

I am trying to debug this https://tests.stockfishchess.org/actions?action=log_message&user=&text=cores

**Comment by vdbergh** [comment]
Thanks. I will fix this.

**Comment by vondele** [comment]
This could possibly happen if the worker sends an update_task, the rundb is updated, but the full transaction fails (e.g. nginx timeout), in which the worker sends the update_task again?

**Comment by vdbergh** [comment]
> This could possibly happen if the worker sends an update_task, the rundb is updated, but the full transaction fails (e.g. nginx timeout), in which the worker sends the update_task again?

No this happens because for performance reasons `update_task()` and `request_task()` are not synchronized. But with PR #2020 they are at least partially synchronized so that we can now do something in `request_task()`. See #2021 .

**Pull request merged**
