### PR TITLE
fix https://github.com/official-stockfish/fishtest/issues/2095 by cha…

### PR DESCRIPTION
**Pull request by peregrineshahin**
…anging skeleton to a message with retry button

image

image

### CODE REVIEW

**Comment by ppigazzini** [comment]
image

**Comment by peregrineshahin** [comment]
is it fixed now?

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV with:
```diff
-@view_config(route_name="tests_machines", http_cache=10, renderer="machines.mak")
+@view_config(route_name="tests_machines", http_cache=0, renderer="machines.mak")
 def tests_machines(request):
+    time.sleep(40)
     return {"machines_list": request.rundb.get_machines()}

```

image

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin

**Pull request merged**
