### PR TITLE
Avoid saving the host_url in the db with every task.

### PR DESCRIPTION
**Pull request by vdbergh**

### CODE REVIEW

**Comment by ppigazzini** [comment]
DEV updated.

**Comment by vdbergh** [comment]
It seems to have been fixed.

**Comment by ppigazzini** [comment]
Two different runs, without and with the PR
image

**Review by ppigazzini — APPROVED** [review]
LGTM on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh :)

**Pull request merged**
