### PR TITLE
Introduce a schema for the rundb.

### PR DESCRIPTION
**Pull request by vdbergh**
Validation is done after the creation of runs and before writing finished runs to disk. If a finished run fails validation then this is logged but the run is otherwise treated normally.
    
No attempt has been made to make the schema as tight as possible. For example most numbers should be positive but this constraint is ignored by the schema. The main purpose of the schema is to document the structure of the rundb. The reason it is also used for validation in some cases is to ensure that if the structure of the rundb changes then the schema is updated to reflect this change.
    
For a description of the schema format see the README.md file of https://github.com/vdbergh/vtjson
    
The validation code is included in this PR but it can be installed as an independent package via
    
pip install vtjson
    
Validating a run with 500 tasks (which is a lot these days) takes 12 ms on an AWS t2.micro using Python 3.11.

The schema for the recent run objects is
```python
import math
from datetime import datetime
from bson.objectid import ObjectId
from vtjson import ip_address, number, regex, url

net_name = regex("nn-[a-z0-9]{12}.nnue", name="net_name")
tc = regex(r"([1-9]\d*/)?\d+(\.\d+)?(\+\d+(\.\d+)?)?", name="tc")
str_int = regex(r"[1-9]\d*", name="str_int")
sha = regex(r"[a-f0-9]{40}", name="sha")
country_code = regex(r"[A-Z][A-Z]", name="country_code")
run_id = regex(r"[a-f0-9]{24}", name="run_id")

worker_info_schema = {
    "uname": str,
    "architecture": [str, str],
    "concurrency": int,
    "max_memory": int,
    "min_threads": int,
    "username": str,
    "version": int,
    "python_version": [int, int, int],
    "gcc_version": [int, int, int],
    "compiler": {"clang++", "g++"},
    "unique_key": str,
    "modified": bool,
    "ARCH": str,
    "nps": number,
    "near_github_api_limit": bool,
    "remote_addr": ip_address,
    "country_code": {country_code, "?"},
}

schema = {
    "wins": int,
    "losses": int,
    "draws": int,
    "crashes": int,
    "time_losses": int,
    "pentanomial": [int, int, int, int, int],
}

results_schema = {
    "_id?": ObjectId,
    "start_time": datetime,
    "last_updated": datetime,
    "tc_base": number,
    "base_same_as_master": bool,
    "results_stale?": bool,  # Will go away soon
    "rescheduled_from?": run_id,
    "approved": bool,
    "approver": str,
    "finished": bool,
    "deleted": bool,
    "failed": bool,
    "is_green": bool,
    "is_yellow": bool,
    "workers?": int,  # Will become non-optional
    "cores?": int,  # Will become non-optional
    "results": results_schema,
    "results_info?": {
        "style": str,
        "info": [str, ...],
    },
    "args": {
        "base_tag": str,
        "new_tag": str,
        "base_net": net_name,
        "new_net": net_name,
        "num_games": int,
        "tc": tc,
        "new_tc": tc,
        "book": str,
        "book_depth": str_int,
        "threads": int,
        "resolved_base": sha,
        "resolved_new": sha,
        "msg_base": str,
        "msg_new": str,
        "base_options": str,
        "new_options": str,
        "info": str,
        "base_signature": str_int,
        "new_signature": str_int,
        "username": str,
        "tests_repo": url,
        "auto_purge": bool,
        "throughput": number,
        "itp": number,
        "priority": number,
        "adjudication": bool,
        "sprt?": {
            "alpha": 0.05,
            "beta": 0.05,
            "elo0": number,
            "elo1": number,
            "elo_model": "normalized",
            "state": {"", "accepted", "rejected"},
            "llr": number,
            "batch_size": int,
            "lower_bound": -math.log(19),
            "upper_bound": math.log(19),
            "lost_samples?": int,
            "illegal_update?": int,
            "overshoot?": {
                "last_update": int,
                "skipped_updates": int,
                "ref0": number,
                "m0": number,
                "sq0": number,
                "ref1": number,
                "m1": number,
                "sq1": number,
            },
        },
        "spsa?": {
            "A": number,
            "alpha": number,
            "gamma": number,
            "raw_params": str,
            "iter": int,
            "num_iter": int,
            "params": [
                {
                    "name": str,
                    "start": number,
                    "min": number,
                    "max": number,
                    "c_end": number,
                    "r_end": number,
                    "c": number,
                    "a_end": number,
                    "a": number,
                    "theta": number,
                },
                ...,
            ],
            "param_history?": [
                [{"theta": number, "R": number, "c": number}, ...],
                ...,
            ],
        },
    },
    "tasks": [
        {
            "num_games": int,
            "active": bool,
            "last_updated": datetime,
            "start": int,
            "residual?": number,
            "residual_color?": str,
            "bad?": True,
            "stats": results_schema,
            "worker_info": worker_info_schema,
        },
        ...,
    ],
    "bad_tasks?": [
        {
            "num_games": int,
            "active": False,
            "last_updated": datetime,
            "start": int,
            "residual": number,
            "residual_color": str,
            "bad": True,
            "task_id": int,
            "stats": results_schema,
            "worker_info": worker_info_schema,
        },
        ...,
    ],
}
```

### CODE REVIEW

**Comment by vdbergh** [comment]
I have not tested spsa runs and also not (auto)purged runs. 

Note: there may be bugs in the schema so if validation of a finished run fails then a log message is created detailing the issue, but the run is written to disk anyway.

**Comment by vdbergh** [comment]
isort is failing on CI but locally it returns without error for me :cry:

**Comment by vdbergh** [comment]
This is the schema BTW. 

```python
from numbers import Real
from fishtest.validate import ip_address, optional_key, regex, union, url, validate

net_name = regex("nn-[a-z0-9]{12}.nnue", name="net_name")
tc = regex(r"^([1-9]\d*/)?\d+(\.\d+)?(\+\d+(\.\d+)?)?$", name="tc")
str_int = regex(r"[1-9]\d*", name="str_int")
sha = regex(r"[a-f0-9]{40}", name="sha")
country_code = regex(r"[A-Z][A-Z]", name="country_code")
run_id = regex(r"[a-f0-9]{24}", name="run_id")

worker_info_schema = {
    "uname": str,
    "architecture": [str, str],
    "concurrency": int,
    "max_memory": int,
    "min_threads": int,
    "username": str,
    "version": int,
    "python_version": [int, int, int],
    "gcc_version": [int, int, int],
    "compiler": union("clang++", "g++"),
    "unique_key": str,
    "modified": bool,
    "ARCH": str,
    "nps": Real,
    "near_github_api_limit": bool,
    "remote_addr": ip_address,
    "country_code": union(country_code, "?"),
}

results_schema = {
    "wins": int,
    "losses": int,
    "draws": int,
    "crashes": int,
    "time_losses": int,
    "pentanomial": [int, int, int, int, int],
}

schema = {
    optional_key("_id"): ObjectId,
    "start_time": datetime,
    "last_updated": datetime,
    "tc_base": Real,
    "base_same_as_master": bool,
    optional_key("results_stale"): bool,
    optional_key("rescheduled_from"): run_id,
    "approved": bool,
    "approver": str,
    "finished": bool,
    "deleted": bool,
    "failed": bool,
    "is_green": bool,
    "is_yellow": bool,
    optional_key("workers"): int,
    optional_key("cores"): int,
    "results": results_schema,
    optional_key("results_info"): {
        "style": str,
        "info": list[str],
    },
    "args": {
        "base_tag": str,
        "new_tag": str,
        "base_net": net_name,
        "new_net": net_name,
        "num_games": int,
        "tc": tc,
        "new_tc": tc,
        "book": str,
        "book_depth": str_int,
        "threads": int,
        "resolved_base": sha,
        "resolved_new": sha,
        "msg_base": str,
        "msg_new": str,
        "base_options": str,
        "new_options": str,
        "info": str,
        "base_signature": str_int,
        "new_signature": str_int,
        "username": str,
        "tests_repo": url,
        "auto_purge": bool,
        "throughput": Real,
        "itp": Real,
        "priority": Real,
        "adjudication": bool,
        optional_key("sprt"): {
            "alpha": Real,
            "beta": Real,
            "elo0": Real,
            "elo1": Real,
            "elo_model": union("BayesElo", "logistic", "normalized"),
            "state": union("", "accepted", "rejected"),
            "llr": Real,
            "batch_size": int,
            "lower_bound": Real,
            "upper_bound": Real,
            optional_key("lost_samples"): int,
            optional_key("illegal_update"): int,
            optional_key("overshoot"): {
                "last_update": int,
                "skipped_updates": int,
                "ref0": Real,
                "m0": Real,
                "sq0": Real,
                "ref1": Real,
                "m1": Real,
                "sq1": Real,
            },
        },
        optional_key("spsa"): {
            "A": int,
            "alpha": Real,
            "gamma": Real,
            "raw_params": str,
            "iter": int,
            "num_iter": int,
            "params": list[
                {
                    "name": str,
                    "start": Real,
                    "min": Real,
                    "max": Real,
                    "c_end": Real,
                    "r_end": Real,
                    "c": Real,
                    "a_end": Real,
                    "a": Real,
                    "theta": Real,
                },
            ],
            optional_key("param_history"): list[
                list[{"theta": Real, "R": Real, "c": Real}],
            ],
        },
    },
    "tasks": list[
        {
            "num_games": int,
            "active": bool,
            "last_updated": datetime,
            "start": int,
            optional_key("residual"): Real,
            optional_key("residual_color"): str,
            optional_key("bad"): True,
            "stats": results_schema,
            "worker_info": worker_info_schema,
        }
    ],
    optional_key("bad_tasks"): list[
        {
            "num_games": int,
            "active": False,
            "last_updated": datetime,
            "start": int,
            "residual": Real,
            "residual_color": str,
            "bad": True,
            "task_id": int,
            "stats": results_schema,
            "worker_info": worker_info_schema,
        }
    ],
}
```

**Comment by vdbergh** [comment]
isort keeps failing on CI. Maybe it would be good to print the version number and to pass the --df flag so that we get feedback about what the CI isort considers wrong.

**Comment by peregrineshahin** [comment]
black is ran before isort.
<https://github.com/peregrineshahin/fishtest/pull/5>
```
 python -m black --exclude='env|packages' .
 python -m isort --profile black --skip env --skip venv --skip worker/packages .
```  
> isort keeps failing on CI. Maybe it would be good to print the version number and to pass the --df flag so that we get feedback about what the CI isort considers wrong.

**Comment by vdbergh** [comment]
I run black as well. black is not failing on CI.

**Comment by peregrineshahin** [comment]
https://github.com/peregrineshahin/fishtest/pull/5/commits/d7eb4bc788a9b9d14c04791137189384d7a40d8b
this fixes the issue on my repo

**Comment by vdbergh** [comment]
I made a github repository with the validation code https://github.com/vdbergh/validate. The corresponding Readme.md serves as documentation.

**Comment by vdbergh** [comment]
I now did locally an SPSA test. Everything seems ok. Purging remains to be checked.

**Comment by vdbergh** [comment]
> [peregrineshahin@d7eb4bc](https://github.com/peregrineshahin/fishtest/commit/d7eb4bc788a9b9d14c04791137189384d7a40d8b) this fixes the issue on my repo

Thanks! I'll have a look.

**Comment by vdbergh** [comment]
`isort` is ok now. I added the `--df` myself to the CI `isort` to get some feedback. I hope that's ok.

**Comment by vdbergh** [comment]
I discovered where the `isort` troubles come from. The actions of `isort` depends on the root directory from where you run it. So you cannot just do `isort --profile black *.py` in a directory. I guess this makes some sense since `isort` has to discover some properties of the modules.

**Comment by vdbergh** [comment]
I discovered a PyPi package that is quite similar in spirit to vtjson https://pypi.org/project/json-checker/ . Last update was 4 years ago but perhaps the author considered in "finished".

**Comment by vdbergh** [comment]
I have drafted this since the package `vtjson` has evolved a lot and I must update this PR.

**Comment by Disservin** [comment]
I'm not much into the loop but is it possible we get a requirements.txt in the future? Personally I think it might be better if we use the library from pip instead of including it in the source code and having to "maintain" two versions of it?

Also the license information is missing for vtjson?

**Comment by vdbergh** [comment]
Sure it would be more convenient to install the package directly from pip.

It wasn't clear to me how to deal with upgrades but it would be just like a new index. If a PR would depend on a newer version of vtjson then one can state this in the commit message, and @ppigazzini can perform the upgrade manually.

**Comment by vdbergh** [comment]
I put `vtjson` in `setup.py` but I did not test it (I am afraid of ruining my Fishtest install).

**Comment by ppigazzini** [comment]
DEV updated with the new setup.

**Comment by vdbergh** [comment]
Ignore last commit.

**Comment by vdbergh** [comment]
I had forgotten to replace `fishtest.vtjson` by just `vtjson`. This has been fixed now. I checked that it works with the pip installed package.

**Comment by vdbergh** [comment]
@Disservin Yes the file `vtjson.py` defines a variable `__version__` which is referred to in `pyproject.toml`. It is now 1.3.5 but these numbers don't mean much currently. There is also a license file. It is on github and it is also installed with the source distribution.

**Comment by Disservin** [comment]
> @Disservin Yes the file `vtjson.py` defines a variable `__version__` which is referred to in `pyproject.toml`. It is now 1.3.5 but these numbers don't mean much currently. There is also a license file. It is on github and it is also installed with the source distribution.

Yeah regarding the version my main concern is that right now it's not fixed to a certain (major) version so in case of breaking changes a fresh installation will pick up a different version than what i.e. production currently has? This also applies to the other packages currently used I guess?

**Comment by ppigazzini** [comment]
PROD running the the updated setup, thank you @vdbergh :)

**Comment by vdbergh** [comment]
@ppigazzini Can you have a look if there is a log entry on DEV for this run https://dfts-0.pigazzini.it/tests/view/656c8907d64928f5629a6b47 (there shouldn't be...)? It was purged and I did not test purged runs.

**Comment by vdbergh** [comment]
```
run['tasks'][1]['pending']
```
I thought the pending flag was retired long ago... I will investigate.

**Comment by vdbergh** [comment]
It happens in `tests_modify`. There is some left over code that still sets the pending flag.
```
        existing_games = 0
        for chunk in run["tasks"]:
            existing_games += chunk["num_games"]
            if "stats" in chunk:
                stats = chunk["stats"]
                total = stats["wins"] + stats["losses"] + stats["draws"]
                if total < chunk["num_games"]:
                    chunk["pending"] = True
```

**Comment by peregrineshahin** [comment]
https://github.com/official-stockfish/fishtest/pull/1805
Please check this PR there is not intent to retire the pending flag.
This is unfortunately still not merged yet

**Comment by vdbergh** [comment]
I made a PR that removes the dead code. I have not tested since I am in the middle of something.

**Pull request merged**
