### PR TITLE
Optimize the construction of the main page a little bit.

### PR DESCRIPTION
**Pull request by vdbergh**
Also: remove some dead code while there.

### CODE REVIEW

**Comment by ppigazzini** [comment]
As usual I loaded a DB bkp on DEV, approved a new test and joined few workers. The home page does not update, no errors in logs.
I will try to load master.

**Comment by vdbergh** [comment]
> As usual I loaded a DB bkp on DEV, approved a new test and joined few workers. The home page is stuck with the DB data, no errors in logs. I will try to load master... master fixes the issue. I restart from scratch.
> 
Strange. I tested locally and things seemed ok.

**Comment by ppigazzini** [comment]
I posted the image of the home page, it shows the data from the DB (112 machines connected, 22 active tests etc).
BTW very rarely a restore from a DB backup goes crazy, I'm reloading from scratch.

**Comment by vdbergh** [comment]
You seem correct. The homepage does not update.

**Comment by ppigazzini** [comment]
I reloaded the DB and the PR, I will schedule a new test with high priority and join some workers.

**Comment by vdbergh** [comment]
It updates slowly but it does update. There are 56 runs so it takes some time before a run in the cache of the main instance is written to disk.

I am susprised master behaves differently.

**Comment by vdbergh** [comment]
Post crossed...

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @vdbergh

**Comment by ppigazzini** [comment]
Same issue on DEV with master.
Loaded a DB backup, added and approved a test, joined a worker, home page stuck. The logs shows that there is only 1 active worker, but it shows also that some activity for an invalid run_id (?!?). After a couple of server restarts, the issue seems fixed.

```yaml
Jun 16 22:53:37 dfts-0 pserve[30292]: Clean_wtt_map: 0 active workers...
Jun 16 22:53:37 dfts-0 pserve[30292]: Validate_random_run: validated cache run 66689317d3bda2281d5a6d23...
Jun 16 22:56:33 dfts-0 pserve[30292]: Clean_wtt_map: 0 active workers...
Jun 16 22:56:33 dfts-0 pserve[30292]: Validate_random_run: validated cache run 6667a32b028a234afef5c40c...
Jun 16 22:59:37 dfts-0 pserve[30292]: Clean_wtt_map: 0 active workers...
Jun 16 22:59:37 dfts-0 pserve[30292]: Validate_random_run: validated cache run 6667bf46028a234afef5c423...
Jun 16 23:02:42 dfts-0 pserve[30292]: Clean_wtt_map: 0 active workers...
Jun 16 23:02:42 dfts-0 pserve[30292]: Validate_random_run: validated cache run 66500384a86388d5e27d8edd...
Jun 16 23:05:49 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:05:49 dfts-0 pserve[30292]: Validate_random_run: validated cache run 665a7eea062b2c3cf814fe40...
Jun 16 23:08:55 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:08:55 dfts-0 pserve[30292]: Validate_random_run: validated cache run 66678372028a234afef5c3fe...
Jun 16 23:11:51 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:11:51 dfts-0 pserve[30292]: Validate_random_run: validated cache run 6667d3ae028a234afef5c43a...
Jun 16 23:14:44 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:14:44 dfts-0 pserve[30292]: Validate_random_run: validated cache run 665ba0b744e8416a9cdc188d...
Jun 16 23:17:38 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:17:38 dfts-0 pserve[30292]: Validate_random_run: validated cache run 6667a32b028a234afef5c40c...
Jun 16 23:20:13 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Jun 16 23:20:13 dfts-0 pserve[30292]: Clean_wtt_map: 1 active workers...
Jun 16 23:20:13 dfts-0 pserve[30292]: flush
Jun 16 23:20:14 dfts-0 pserve[30292]: ...............................................done
Jun 16 23:20:16 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Jun 16 23:20:16 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Jun 16 23:20:18 dfts-0 pserve[19241]: Starting server in PID 19241.
Jun 16 23:20:19 dfts-0 pserve[19241]: /api/update_task: Invalid run_id: 66689317d3bda2281d5a6d23
Jun 16 23:20:19 dfts-0 pserve[19241]: /api/failed_task: Invalid run_id: 66689317d3bda2281d5a6d23
Jun 16 23:20:19 dfts-0 pserve[19241]: /api/upload_pgn: Invalid run_id: 66689317d3bda2281d5a6d23
Jun 16 23:20:58 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Jun 16 23:20:58 dfts-0 pserve[19241]: flush
Jun 16 23:20:58 dfts-0 pserve[19241]: .............................................done
Jun 16 23:20:59 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Jun 16 23:21:02 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Jun 16 23:21:05 dfts-0 pserve[19326]: Starting server in PID 19326.
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 266 worker: Sylvain27-3cores-7730e220-4a6c
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 269 worker: ChessDBCN-4cores-128b55ec-a026
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 270 worker: ChessDBCN-4cores-651c1fe4-c328
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 271 worker: mgrabiak-3cores-d774a6db-3a50
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 272 worker: teenychess-3cores-664b0771-821c
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666c6c42602682471b064e66 task_id: 273 worker: ChessDBCN-4cores-3d0db293-4425
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 363 worker: leszek-15cores-e3af64da-9adc*
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 364 worker: ChessDBCN-8cores-1b40cd74-dccb
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 365 worker: ChessDBCN-8cores-16f0cef0-c1e3
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 367 worker: ChessDBCN-8cores-34112304-f5ce
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 368 worker: ChessDBCN-8cores-3c0147a2-292a
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 369 worker: linrock-16cores-015681e5-dde7
Jun 16 23:22:02 dfts-0 pserve[19326]: dead task: run: https://tests.stockfishchess.org/tests/view/666bce45602682471b064e15 task_id: 370 worker: ChessDBCN-8cores-1e569721-c224
```

**Comment by vdbergh** [comment]
Was the there a worker running while the db was running? That could explain the invalid run id.

**Comment by vdbergh** [comment]
I need to think while the homepage can get stuck.

**Comment by ppigazzini** [comment]
No. I added the worker a couple of hours after the DB reload and after having added/approved the new test.

**Comment by vdbergh** [comment]
I have the feeling that the flush_buffers task was not running. That would explain both the invalid run idea and the stuck main page.

Now the question is how this can possibly happen (other tasks were doing fine).

**Comment by vdbergh** [comment]
> so the worker got the not existent run_id from the server. 

Yes that’s true. It was in the cache before the restart (it was validated).

**Comment by ppigazzini** [comment]
```bash
$ grep run api.log
2024-06-16 21:03:15.189288+00:00 : run: 66688d8bd3bda2281d5a6d18 task: 245 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:08:45.231763+00:00 : run: 66689317d3bda2281d5a6d23 task: 231 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:12:55.369803+00:00 : run: 66688d8bd3bda2281d5a6d18 task: 246 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:16:17.235321+00:00 : run: 66689317d3bda2281d5a6d23 task: 232 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:20:35.337893+00:00 : run: 666f52e51fc9558a590c3fc6 task: 0 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:25:49.627972+00:00 : run: 666f52e51fc9558a590c3fc6 task: 1 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:29:27.346437+00:00 : run: 666f52e51fc9558a590c3fc6 task: 2 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:33:20.228860+00:00 : run: 666f52e51fc9558a590c3fc6 task: 3 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:37:38.331599+00:00 : run: 666f52e51fc9558a590c3fc6 task: 4 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:41:43.342343+00:00 : run: 666f52e51fc9558a590c3fc6 task: 5 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:45:59.524741+00:00 : run: 666f52e51fc9558a590c3fc6 task: 6 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:49:54.417712+00:00 : run: 666f52e51fc9558a590c3fc6 task: 7 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
2024-06-16 21:53:51.296573+00:00 : run: 666f52e51fc9558a590c3fc6 task: 8 size: 174 tc: 1+0.01 concurrency: 3 threads: 1 [ num_games : 3200000 ]
```

**Comment by vdbergh** [comment]
Can you grep for the invalid idea with a few lines of context?

**Comment by ppigazzini** [comment]
The TC 1+0.01 suggest that they are tests added by me on DEV, some leftover before the DB reload ?!?
```yaml
$ less api.log
2024-06-16 21:03:13.600819+00:00 :   0.16 ms (s)   184.64 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-16 21:03:13.736321+00:00 :   0.14 ms (s)   132.69 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-16 21:03:14.757015+00:00 :   0.20 ms (s)   134.86 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-16 21:03:15.188764+00:00 :   2.19 ms (s)   127.86 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-16 21:03:15.189288+00:00 : run: 66688d8bd3bda2281d5a6d18 task: 245 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:05:14.073855+00:00 :   1.67 ms (s)   140.36 ms (w)  https://dfts-0.pigazzini.it:443/api/beat
2024-06-16 21:05:25.129480+00:00 :   1.11 ms (s)   137.81 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:05:32.278144+00:00 :   1.01 ms (s)   138.41 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:05:42.418393+00:00 :   1.25 ms (s)   126.40 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:05:52.602523+00:00 :   1.89 ms (s)   169.33 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:03.728271+00:00 :   1.09 ms (s)   110.67 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:10.845410+00:00 :   1.05 ms (s)   106.65 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:19.986335+00:00 :   1.08 ms (s)   128.51 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:30.126061+00:00 :   0.93 ms (s)   124.89 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:38.290036+00:00 :   1.05 ms (s)   152.26 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:49.447796+00:00 :   0.96 ms (s)   141.83 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:06:57.589751+00:00 :   0.92 ms (s)   129.28 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:05.734055+00:00 :   0.89 ms (s)   132.33 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:15.877819+00:00 :   2.19 ms (s)   129.51 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:23.017568+00:00 :   0.96 ms (s)   129.41 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:33.182892+00:00 :   0.96 ms (s)   150.68 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:43.330805+00:00 :   1.48 ms (s)   133.64 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:07:51.493942+00:00 :   0.99 ms (s)   151.05 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:01.657914+00:00 :   1.85 ms (s)   150.16 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:12.801496+00:00 :   1.05 ms (s)   127.76 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:21.933071+00:00 :   0.91 ms (s)   118.22 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:30.079460+00:00 :   1.28 ms (s)   134.28 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:44.242743+00:00 :   1.12 ms (s)   144.26 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:08:44.661782+00:00 :  99.40 ms (s)   313.16 ms (w)  https://dfts-0.pigazzini.it:443/api/upload_pgn
2024-06-16 21:08:44.791589+00:00 :   0.33 ms (s)   128.31 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-16 21:08:45.231200+00:00 :   1.97 ms (s)   124.72 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-16 21:08:45.231763+00:00 : run: 66689317d3bda2281d5a6d23 task: 231 size: 176 tc: 1+0.01 concurrency: 3 threads: 1 [ sprt : 800000 ]
2024-06-16 21:09:30.478173+00:00 :   1.91 ms (s)   144.61 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task
2024-06-16 21:09:42.608202+00:00 :   1.50 ms (s)   113.48 ms (w)  https://dfts-0.pigazzini.it:443/api/update_task

```

**Comment by ppigazzini** [comment]
It seems that I must restart fishtest to clear the cache after a DB reload.

**Comment by vdbergh** [comment]
> The TC 1+0.01 suggest that they are tests added by me on DEV, some leftover before the DB reload ?!?

Would that be possible? However that does still not explain why these runs were never written to disk… 

I see no other solution than to instrument flush_buffers.

**Comment by vdbergh** [comment]
> It seems that I must restart fishtest to clear the cache after a DB reload.

Yes if the cache is not in sync with the db then strange things can happen (I still don’t fully understand it though).

**Comment by ppigazzini** [comment]
The runs were written to disk, but I loaded a DB backup from AWS S3. I never saw this happens in the past (or the issue auto solved in few minutes).

**Comment by vdbergh** [comment]
Yes but a dirty run in the cache will be written to disk. If a worker gets a task from the run then the run becomes dirty…

**Comment by ppigazzini** [comment]
But a dirty run (existing only in cache) is able to update a run that is not in the DB?

**Comment by vdbergh** [comment]
> But a dirty run (existing only in cache) is able to update a run that is not in the DB? 

It seems I was wrong. It cannot since it uses replace to update the db. However in that case there should have been an exception I think which should have been logged…

**Comment by ppigazzini** [comment]
Something is still wrong.
1. stop worker
2. drop DB
3. restart fishtest to empty the cache
4. load a new DB
5. build worker from scratch and join

The worker does not get a task...


```yaml
Obtaining version info for /home/usr00/_git/__test_folder00/fishtest/worker/testing/cutechess-cli ...
Found cutechess-cli 1.2.0
Downloading https://raw.githubusercontent.com/official-stockfish/fishtest/master/worker/sri.txt
worker.py has been modified!
games.py has been modified!
This worker is tainted...
Using g++ 13.2.0
UUID: a14bb4a2-ac34-46bf-a6d1-441e8a2c117b
Start heartbeat
Current time is 2024-06-17 10:22:54.684170+00:00 UTC (local offset: +02:00)
Verify worker version...
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 125.68ms (server: 0.17ms)
Remaining number of GitHub api calls = 5000
Fetching task...
Post request https://dfts-0.pigazzini.it:443/api/request_task handled in 114.89ms (server: 6.21ms)
No tasks available at this time, waiting...
Waiting 15.0 seconds before retrying
Current time is 2024-06-17 10:23:10.224736+00:00 UTC (local offset: +02:00)
Verify worker version...
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 140.17ms (server: 0.23ms)
Remaining number of GitHub api calls = 5000
Fetching task...
Post request https://dfts-0.pigazzini.it:443/api/request_task handled in 111.57ms (server: 2.29ms)
No tasks available at this time, waiting...
Waiting 30.0 seconds before retrying
Current time is 2024-06-17 10:23:40.805255+00:00 UTC (local offset: +02:00)
Verify worker version...
Post request https://dfts-0.pigazzini.it:443/api/request_version handled in 129.50ms (server: 0.21ms)
Remaining number of GitHub api calls = 5000
Fetching task...
Post request https://dfts-0.pigazzini.it:443/api/request_task handled in 127.36ms (server: 1.97ms)
No tasks available at this time, waiting...
Waiting 60.0 seconds before retrying
```

```yaml
$ less api.log
2024-06-17 10:22:53.643782+00:00 :   2.05 ms (s)   392.67 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:22:53.790822+00:00 :   0.18 ms (s)   143.80 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:22:54.810268+00:00 :   0.17 ms (s)   125.68 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:22:55.210004+00:00 :   6.21 ms (s)   114.89 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-17 10:23:10.365482+00:00 :   0.23 ms (s)   140.17 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:23:10.777200+00:00 :   2.29 ms (s)   111.57 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-17 10:23:40.935198+00:00 :   0.21 ms (s)   129.50 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:23:41.363318+00:00 :   1.97 ms (s)   127.36 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-17 10:24:41.579272+00:00 :   0.24 ms (s)   154.50 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:24:42.061906+00:00 :   2.66 ms (s)   143.25 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-17 10:26:42.313557+00:00 :   1.18 ms (s)   160.82 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:26:42.724891+00:00 :   2.13 ms (s)   107.59 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
2024-06-17 10:30:42.998286+00:00 :   1.14 ms (s)   176.69 ms (w)  https://dfts-0.pigazzini.it:443/api/request_version
2024-06-17 10:30:43.418361+00:00 :   1.48 ms (s)   102.44 ms (w)  https://dfts-0.pigazzini.it:443/api/request_task
```

```yaml
Jun 17 11:36:03 dfts-0 systemd[1]: Stopping Fishtest Server port 6543...
Jun 17 11:36:03 dfts-0 pserve[19326]: flush
Jun 17 11:36:04 dfts-0 pserve[19326]: ........................................................................................done
Jun 17 11:36:05 dfts-0 systemd[1]: Stopped Fishtest Server port 6543.
Jun 17 11:36:05 dfts-0 systemd[1]: Started Fishtest Server port 6543.
Jun 17 11:36:07 dfts-0 pserve[23179]: Starting server in PID 23179.
Jun 17 11:37:10 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:37:10 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:40:19 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:40:19 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:43:21 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:43:21 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:46:15 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:46:15 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:49:21 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:49:21 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:52:13 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:52:13 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:55:07 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 11:58:04 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 11:58:04 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:00:56 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:00:56 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:04:02 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:04:02 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:06:56 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:06:56 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:10:02 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:10:02 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:13:07 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:16:05 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:16:05 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:19:04 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:19:04 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:22:09 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:22:09 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:25:02 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:25:02 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:28:09 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:28:09 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:31:08 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:31:08 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:34:13 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:34:13 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:37:11 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:37:11 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:40:04 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:40:04 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:43:09 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:43:09 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
Jun 17 12:46:16 dfts-0 pserve[23179]: Clean_wtt_map: 0 active workers...
Jun 17 12:46:16 dfts-0 pserve[23179]: Validate_random_run: no unfinished cache runs. No runs to validate...
```

**Comment by vdbergh** [comment]
I have not read in detail yet what you wrote but I think you should do

1. stop worker
2. stop fishtest
3. drop DB
4. reload DB
5. start fishtest (this will initialize fishtest using the new db)
6. build worker from scratch and join

Maybe this can be relaxed, but in any case it is very important that fishtest is restarted after loading the new db because it does a lot of initialization now (in the method: `update_aggregated_data()`).

**Comment by ppigazzini** [comment]
I confirm that the server is working fine with a restart before and after the DB reload.

**Pull request merged**
