### PR TITLE
remove unnecessary loop

### PR DESCRIPTION
**Pull request by peregrineshahin**
and change list to generator expression

### CODE REVIEW

**Comment by ppigazzini** [comment]
The changes are not equivalent to the original code in subtle ways:
1. the first code returns the run as well (but it's not used in the following code, so the pythonic simplification is OK)
2. only one loop breaks the priority of the checks and mix the checks, this can make more difficult to debug the Event Logs. In my review of this function, I skipped this optimization because this reason, so I'm in difficulty to approve it in this PR.

**Comment by vondele** [comment]
my 2cents, unrelated to an eventual merging, would it make sense to measure once the impact on the server time needed for this function under load?

**Comment by ppigazzini** [comment]
Only a fast test, rn we have little space left.
```
fishtest@tests:~$ df -h
Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop29670p1   99G   85G  9.7G  90% /
none               2.5G     0  2.5G   0% /sys/fs/cgroup
none               2.5G     0  2.5G   0% /dev
tmpfs              2.5G     0  2.5G   0% /dev/shm
tmpfs              2.5G  1.2M  2.5G   1% /run
tmpfs              5.0M     0  5.0M   0% /run/lock
none               2.5G     0  2.5G   0% /run/shm
tmpfs              512M     0  512M   0% /run/user/1000
```

**Comment by vondele** [comment]
should probably work, some workers will need to request a task twice. I can monitor.

What about storing STC tests only for a day?

**Comment by peregrineshahin** [comment]
> 2a. only one loop breaks the priority of the checks and mix the checks, this can make more difficult to debug the Event Logs.
2b. the code is a bit less readable

a) I don't think there is an inherent priority for the checks
b) in case you want another reason to return from this function with an error, it becomes unmaintainable to add yet another loop that is the same to do it, it's not like these two loops are done in a declarative way to make sense of what they are doing there are just duplicate C-like for loops which look bad.

i.e. one can argue that mapping/filtering/reducing adds to the readability and thus can be done twice, not the case here IMO.

**Comment by ppigazzini** [comment]
I have no opinion on how long to retain the PGNs, as I don't know their use. Feel free to open a PR changing the numbers.

https://github.com/official-stockfish/fishtest/blob/1a3928fde2ddbf790a5d313b15fe64a3eb3ea743/server/utils/purge_pgn.py#L70-L86

**Comment by robertnurnberg** [comment]
I think keeping STC just for 1 day, and LTC just for 7 days is reasonable.

Of course, if the fleet would re-appear for extended periods, even that might not be enough to keep the disk from filling up....

**Comment by peregrineshahin** [comment]
This sounds reasonable feel free to override this PR with that, but it's still does not show any edge for having two loops whatsover over one, and also IMO it's confusing and a bad code not to break from loops if the code is already as imperative as a `for` when we know we are already done.

> If a worker contributor has both the issues (workers duplicated and connection limit) the new function could report the connection limit (a low priority warning) before the duplicated workers (higher priority warning, bad setup). A solution will be to complete the loop and report both the issues instead than exit as fast as possible like now with an incomplete report (with the possible wrong priority). In case of worker without issues, the loop is always completed.

**Comment by vdbergh** [comment]
> it's not like these two loops are done in a declarative way to make sense of what they are doing they are just duplicate C-like for loops which look bad.

As usual we disagree... I don't think merging unrelated checks in a single loop necessarily makes the code clearer.

Basically we have two distinct checks, which both accidentally happen to involve the same loop...

**Comment by peregrineshahin** [comment]
> which both accidentally happen to involve the same loop...
accidental occasions are what drive people to generalize code.

**Pull request closed without merging**
