### PR TITLE
add fixed games to the calc_elo API

### PR DESCRIPTION
**Pull request by peregrineshahin**
allow passing nothing for elo0 and elo1, and use the fixed game get_elo function

### CODE REVIEW

**Comment by peregrineshahin** [comment]
BTW, worth noting that the math/logic is identical as other parts in the code, if there is no elo0 and elo1 (fixed-game) another simpler logic is applied.

**Comment by ppigazzini** [comment]
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100
```
Apr 14 11:09:38 dfts-0 pserve[27541]:   File "/home/usr00/fishtest/server/fishtest/api.py", line 432, in calc_elo
Apr 14 11:09:38 dfts-0 pserve[27541]:     return get_elo(results["pentanomial"])
Apr 14 11:09:38 dfts-0 pserve[27541]:            ^^^^^^^
Apr 14 11:09:38 dfts-0 pserve[27541]: NameError: name 'get_elo' is not defined. Did you mean: 'self.get_elo'?
```
fixing that error:
```
Apr 14 11:12:23 dfts-0 pserve[27650]:   File "/home/usr00/fishtest/server/fishtest/api.py", line 432, in calc_elo
Apr 14 11:12:23 dfts-0 pserve[27650]:     return self.get_elo(results["pentanomial"])
Apr 14 11:12:23 dfts-0 pserve[27650]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 14 11:12:23 dfts-0 pserve[27650]: TypeError: ApiView.get_elo() takes 1 positional argument but 2 were given
```

**Comment by peregrineshahin** [comment]
should be fixed, could you please run isort, I don't have pipx..

**Comment by peregrineshahin** [comment]
> should be fixed, could you please run isort, I don't have pipx..

NVM, I figured what it wants through trial and error :P

**Comment by ppigazzini** [comment]
Le me know if all is working as intended.
- sprt
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=0&elo1=2

- numgames
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0&elo1=2
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=0&elo1
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=0
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0

- errors
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=aaa&elo1=aaa
https://dfts-0.pigazzini.it/api/calc_elo?LL=93&LD=18711&DDWL=58877&WD=18739&WW=100&elo0=0&elo1=200

**Comment by peregrineshahin** [comment]
LGTM

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin

**Pull request merged**
