### PR TITLE
Remember query strings

### PR DESCRIPTION
**Pull request by peregrineshahin**
latest simplifications omits the query string, add them natively with `path_qs`

### CODE REVIEW

**Comment by vdbergh** [comment]
So exactly the same code is used in 4 places… Time to refactor! ensure_logged_in() …

**Comment by peregrineshahin** [comment]
> So exactly the same code is used in 4 places… Time to refactor! ensure_logged_in(request) …

done

**Comment by vdbergh** [comment]
One can perhaps even do a bit more?
```python
 userid = request.authenticated_userid
    if not userid:
```
This could be refactored as well (that was the `ensure` part in my suggestion...).

**Comment by vdbergh** [comment]
We could possibly return `user_id` here

https://github.com/official-stockfish/fishtest/blob/16ca7d20dfb58d08a76ca8c2529e0432a72f9922/server/fishtest/views.py#L90-L97

So 
```
user_id = ensure_logged_in(request)
```
in case we need the `user_id` later on.

**Comment by peregrineshahin** [comment]
> 

wouldn't that continue the code in the other case where user_id is None, we want to break off the route funtion?

**Comment by vdbergh** [comment]
I don't think so. If the user is logged in this will return `user_id`. If he is not then `ensure_logged_in()` does not return but the browser will fetch the same page again, now with the user logged in, so that this time `ensure_logged_in()` does return the `user_id`.

**Comment by peregrineshahin** [comment]
do you mean that at any level of nesting functions `return HTTPFound()` will exit all root level function calls?
I'm not sure that how it works. that will work for the user sure, but it will generate server error since the excution will continue after returning from `ensure_logged_in()`?

**Comment by vdbergh** [comment]
Ah yes I think you are right. I guess `return HTTPFound()` will only work if it returns from the view. This makes things more tricky. Sorry about that :frowning_face:

**Comment by vdbergh** [comment]
I think an alternative to return may be to raise an exception. Not sure. Have to run.

**Comment by vdbergh** [comment]
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/views.html#using-a-view-callable-to-do-an-http-redirect

**Comment by ppigazzini** [comment]
DEV updated, no good.
```yaml
Sep 03 11:15:31 dfts-0 pserve[10392]: 2023-09-03 11:15:31,295 ERROR [waitress][waitress-0] Exception while serving /tests/run
Sep 03 11:15:31 dfts-0 pserve[10392]: Traceback (most recent call last):
...
Sep 03 11:15:31 dfts-0 pserve[10392]:   File "/home/usr00/fishtest/server/fishtest/views.py", line 1005, in tests_run
Sep 03 11:15:31 dfts-0 pserve[10392]:     "tests_repo": u.get("tests_repo", ""),
Sep 03 11:15:31 dfts-0 pserve[10392]:                   ^^^^^
Sep 03 11:15:31 dfts-0 pserve[10392]: AttributeError: 'NoneType' object has no attribute 'get'
```

image

**Comment by vdbergh** [comment]
Yes the return needs to be replaced by raise.

**Comment by ppigazzini** [comment]
DEV updated, my first tests look good.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV in my tests

**Comment by ppigazzini** [comment]
PROD updated, thank you @peregrineshahin :)

**Pull request merged**
