### PR TITLE
Do not put results_info in the db.

### PR DESCRIPTION
**Pull request by vdbergh**
Rendered data does not belong in the db.

### CODE REVIEW

**Comment by vdbergh** [comment]
Note that the PRs #2071 #2070 #2069 #2067 all have slight conflicts. I will rebase them when required.

**Comment by vdbergh** [comment]
Drafted this since I see a simple way to achieve the goal.

**Comment by vdbergh** [comment]
Undrafted.

**Comment by vdbergh** [comment]
Rebased!

**Comment by vdbergh** [comment]
Rebased.

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
If I'm not wrong, we can write a script to drop the `run['results_info']` from all the runs in the "runs" collection
```yaml
Jul 04 21:25:39 ns304014 pserve[52240]: The run object 668444967a1863935cee42ba does not validate: run['results_info'] is not in the schema
Jul 04 21:28:45 ns304014 pserve[52240]: Clean_wtt_map: 105 active workers...
Jul 04 21:28:45 ns304014 pserve[52240]: Clean_wtt_map: 106 active workers...
Jul 04 21:28:45 ns304014 pserve[52240]: The run object 6685df348c84573fdb76449d does not validate: run['results_info'] is not in the schema
Jul 04 21:31:49 ns304014 pserve[52240]: Clean_wtt_map: 106 active workers...
Jul 04 21:31:49 ns304014 pserve[52240]: The run object 6684724e7a1863935cee42f9 does not validate: run['results_info'] is not in the schema
```

**Comment by vdbergh** [comment]
Yes we can. After this PR it will just be ignored, so it would be nice to get rid of it.

**Comment by ppigazzini** [comment]
Ok, I will wrote a script to clean the key/value

**Pull request merged**
