### PR TITLE
Clear out confusion in wrong bench message.

### PR DESCRIPTION
**Pull request by peregrineshahin**
The previous message is confusing and vague enough to convey the reversed meaning.

### CODE REVIEW

**Comment by dubslow** [comment]
mb `author` over `user`?

**Comment by peregrineshahin** [comment]
> mb `author` over `user`?

there is the case when the user submits the test on behalf of the author :P

**Review by ppigazzini — APPROVED** [review]
Looks good on DEV

**Comment by ppigazzini** [comment]
Triggered the workers update, thank you @peregrineshahin

**Pull request merged**
